### ISSUE TITLE
Transforms are not being applied to built-in modules

### ISSUE THREAD

**Issue by TuurDutoit** [browserify/browserify#1042]
When you `require()` a built-in module (`events`, for example) somewhere in the code, and use a transform when bundling (uglifyify, for example), the transform is not applied to the built-in module, but it is applied to others.
In this case, everything but the built-in modules are minified.

**Comment by mattdesl** [comment]
@TuurDutoit have you tried `--global-transform=module` command?

**Comment by uptownhr** [comment]
hi everyone,

Although the -g is a solution, it is one that significantly decreases the performance of a build. Depending on the size of your node_modules directory it can take seconds for each update that you do. 

Is there no better alternative? I wish I can specify which node_modules I want browserify to go and transform without using -g. I understand that the maintainer of the node_module can specify the {browserify: {transform: ''} } method but I cannot rely on them to do this all the time and me making changes inside node_modules is wrong as it will not transfer over to other people cloning my repo.

**Comment by goto-bus-stop** [comment]
`-g` and `global: true` are the way to do this; if you need to be more specific you can use a global [tfilter](https://www.npmjs.com/package/tfilter) transform.
