### ISSUE TITLE
testling fails on Opera 10.6

### ISSUE THREAD

**Issue by ljharb** [browserify/browserify#1054]
On Opera 10.6, I get this error:

``` js
Uncaught exception: ReferenceError: Undefined variable: e

Error thrown at line 1, column 230 in s(o, u) in http://localhost:53993/__testling?show=true:
    t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)
called from line 1, column 391 in e(t, n, r) in http://localhost:53993/__testling?show=true:
    s(r[o]);
called from line 1, column 0 in http://localhost:53993/__testling?show=true:
    (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);throw new Error("Cannot find module '"+o+"'")}var f=n[o]={exports:{}};t[o][0].call(f.exports,function(e){var n=t[o][1][e];return s(n?n:e)},f,f.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
```

This doesn't happen in IE 6-11, Opera 11.1, etc, so I assume it's specific to browserify and Opera 10.6. It may be why `testling-ci` seemed to always hang on Opera 10.6 and never complete?

**Comment by Xotic750** [comment]
Just had the same problem when testing on Sauce Labs, Opera 10 fails while all other browser run.

![Opera 10 Fail](https://saucelabs.com/jobs/013f8761099e4b1db0352aecb11333ce/0001screenshot.png)

**Comment by goto-bus-stop** [comment]
I think this patch fixes it: https://github.com/browserify/browser-pack/pull/84

@ljharb does that look good & worth it to you?

**Comment by ljharb** [comment]
Yes, it does: https://github.com/browserify/browser-pack/pull/84#issuecomment-363472939

**Comment by goto-bus-stop** [comment]
📦 16.0.0
