### ISSUE TITLE
Browserify generates invalid standalone bundles for modules with circular dependencies

### ISSUE THREAD

**Issue by nylen** [browserify/browserify#1068]
When bundling a module that contains circular dependencies as a standalone bundle, `browserify` appears to succeed, but generates an invalid bundle which produces the following error upon running:

```
Uncaught Error: Cannot find module './index'
```

I've set up a repository to reproduce the bug at https://github.com/nylen/browserify-bug, here are the repro steps:

``` sh
git clone https://github.com/nylen/browserify-bug.git
cd browserify-bug
npm install
node do-browserify.js
```

Here is the `test` module setup that fails:
- `test/index.js` requires `test/step1.js`
- `test/step1.js` requires `test/index.js` as `require('./index')` (this fails)

Running `browserify` from the command line generates slightly different bundles, but with the same error:

``` sh
browserify -r test -o bundle.js -s test
node bundle.js # fails
```

Making the module either not standalone or specifying the filename succeeds, but I wasn't able to get similar JS code to succeed:

``` sh
browserify -r test -o bundle.js
node bundle.js # works fine

browserify node_modules/test/index.js -o bundle.js -s test
node bundle.js # works fine
```

**Comment by nylen** [comment]
Sorry for the commit reference spam, took me a few tries to get the `request` build passing.

**Comment by LiamKarlMitchell** [comment]
Any idea about a fix for this?

**Comment by nylen** [comment]
:+1: for fixing this.  @substack can you take a look?  I have simple repro steps:

```sh
git clone https://github.com/nylen/browserify-bug.git
cd browserify-bug
npm install
node do-browserify.js
```

**Comment by tkaria** [comment]
Has this been fixed? Or addressed? Didn't see it referenced in the commits.

**Comment by neumino** [comment]
Looks like I ran into this issue too with https://github.com/neumino/reqlite

**Comment by neurosnap** [comment]
I'm running into this issue every once in awhile as well.  It would be great to have better error handling because the outputted error message could send developers down the wrong path.

**Comment by goto-bus-stop** [comment]
Still an issue. I ran into this recently too so I'll take a look when I have time.

**Comment by goto-bus-stop** [comment]
Ah; `indexDeps` has an undefined value, the same as in #1260. Moving there!
