### ISSUE TITLE
Where's the license?

### ISSUE THREAD

**Issue by jmm** [browserify/browserify#1069]
This [LICENSE](https://github.com/substack/node-browserify/commits/3ecfb63df819aa1b7704f61bdaab5bdd68314ff1/LICENSE) file feels like it's missing something...like the copyright and license for browserify itself. (I'm aware of what the readme says about the license.)

**Comment by maeslor** [comment]
Yes, it seems like the LICENSE file is referring to just some parts, where it just should use a single correct version of the MIT license.
