### ISSUE TITLE
Error message should indicate which file triggered the error

### ISSUE THREAD

**Issue by cowwoc** [browserify/browserify#1083]
I am getting this error message when running browserify:

`Cannot find module 'domReady' from 'C:\Users\Gili\Documents\foo\frontend\src\main\webapp\com\foo\frontend\page'`

Meaning, if file X invokes `require('domReady')` while fails to resolve, I am expecting the error message to contain the absolute path to X. Otherwise, these errors are very difficult to resolve (since `domReady` is referenced many times by different files).

**Comment by jmm** [comment]
See substack/node-resolve/issues/60 and substack/node-resolve/pull/64.

**Comment by cowwoc** [comment]
@jmm If this is fixed in node-resolve, will it magically get fixed in node-browserify as well (meaning, is the latter built on top of the former)? Or do you need to fix this separately?

**Comment by jmm** [comment]
These are the steps:

* `[X]` get node-browser-resolve to [pass through opts to node-resolve](https://github.com/defunctzombie/node-browser-resolve/pull/52)
* `[  ]` get substack/node-resolve#64 merged and pushed to npm
* `[  ]` get node-browser-resolve to bump node-resolve version
* `[  ]` get browserify to bump node-browser-resolve version

**Comment by cowwoc** [comment]
Got it. Thanks for the clarification :)

**Comment by jmm** [comment]
No problem!

**Comment by jmm** [comment]
Made a plugin for this: https://www.npmjs.com/package/browserify-require-not-found-parent

**Comment by A-312** [comment]
> * `[  ]` get [browserify/resolve#64](https://github.com/browserify/resolve/pull/64) merged and pushed to npm

64 is closed. :(

**Comment by goto-bus-stop** [comment]
I believe this is finally done in 16.5.2 😄
