### ISSUE TITLE
Minify "exports" property

### ISSUE THREAD

**Issue by dsuckau** [browserify/browserify#1121]
Hey folks,

I use browserify a lot in combination with minification. I already know `bundle-collapser` to minify the module names in `require()` calls.

But I am still thinking about if there is possibility to minify the `module.exports` property. I have tons of `a.exports` in my minified bundle, of course, because the minifier does not change object properties. Browserify relies on the existence of `exports`, but I think in the browser it would not matter if it would be called `module.x` or something.

Is there already an option/plugin to achieve this? Or am I even totally missing anything that conflicts with my idea?

**Comment by danzajdband** [comment]
If you gzip your js (and you should), the gzip format will compress the `module.exports` string really well if it's repeated so many times. I wouldn't worry about it.

**Comment by dsuckau** [comment]
Yes, you're right, but our company sells elearning courses. That are, in fact, micro websites based on a JavaScript framework with changing config JSON, CSS and images. That micro websites get delivered to the customer, we have no influence on how they will be hosted. Often they will only be available in the internal network of the customer.

**Comment by nikku** [comment]
Switching on compression became a best practice on the web. I'd suggest my customers to do it and wouldn't care too much about my applications bundle size if they don't.
