### ISSUE TITLE
Maximum call stack size exceeded when trying to minify

### ISSUE THREAD

**Issue by dvprz** [browserify/browserify#1148]
Hello, everyone. I have a file with 58,511 lines and about 1.8MB in size. I'm trying to minify it to reduce some of the size but my build process hiccups when it gets to this part. Below is my gulp task..

``` javascript
var browserified = transform(function(filename) {
        return browserify(filename)
            .bundle();
    });

    return gulp.src(['./index.js'])
        .pipe(browserified)
        .pipe(uglify())
        .pipe(gulp.dest('./js'));
```

Is this just not possible? Am I missing something? Thank you.

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one with some more context if this is still relevant.
