### ISSUE TITLE
adding external bundles prevents main bundle from bundling

### ISSUE THREAD

**Issue by defunctzombie** [browserify/browserify#1171]
bundle bundle bundle bundle... haha

It seems that when you add another (unbuilt) bundle (bundle1) to a browesrify bundle (bundle 2) and then try to build bundle 2, it will just do nothing (no error, nothing). If you remove the line that reads `bundle2.external(bundle1)` then the bundle function call works and the callback is called (no error).

code to reproduce https://github.com/defunctzombie/tmp-browserify-fail:

``` js
var browserify = require('browserify');

var pubdir = __dirname;

var opt = {
    debug: true,
    basedir: pubdir,
    exposeAll: true
};

var bundle1 = browserify(opt);
var name = pubdir + '/js/foo.js';
bundle1.require(name, { entry: true, expose: name, basedir: pubdir });

var bundle2 = browserify({
    debug: true,
    basedir: pubdir,
    entries: [ pubdir + '/js/baz.js' ]
});

// adding and removing this line causes failure //
//bundle2.external(bundle1);

bundle2.bundle(function(err, src) {
    console.log(err, src);
});
```

**Comment by marcello3d** [comment]
Did some testing here, this fails all the way back to 5.10.0 (5.0 - 5.9.3 don't have `.external`).

**Comment by marcello3d** [comment]
Cause appears to be https://github.com/substack/node-browserify/blob/9.0.3/index.js#L197 is incremented, but this isn't called: https://github.com/substack/node-browserify/blob/9.0.3/index.js#L230

I can fix the above test by adding a call to `bundle1.bundle()` above (or below) `bundle2.bundle(...)`.

**Comment by substack** [comment]
It looks like a streams2 issue since bundle1 is never consumed so the hooks that .external() uses never get processed. Is there a use case where you would generate a bundle and never consume it?

**Comment by defunctzombie** [comment]
@substack Yea, this came up in enchilada tests. It was weird because we do still consume the first bundle in the tests but when going to consume the second it still didn't work.

https://github.com/defunctzombie/node-enchilada/blob/master/test/routes.js#L51-L80

The example I created in the failing repo was derived from this test but made to be much simpler and avoid going through enchilada test and module code.

**Comment by marcello3d** [comment]
@substack it happens even if bundle1 is bundled first:
```js
... snip ...
// adding and removing this line causes failure //
bundle2.external(bundle1);
bundle1.bundle(function(err,src) {
    bundle2.bundle(function(err, src) {
        console.log(err,src);
    });
})
```

The only scenario that works if they're both being bundled simultaneously (which seems odd):
```js
... snip ...
// adding and removing this line causes failure //
bundle2.external(bundle1);
bundle1.bundle()
bundle2.bundle(function(err, src) {
    console.log(err, src);
});
```

**Comment by defunctzombie** [comment]
@substack any more thoughts on this?

**Comment by marcello3d** [comment]
I would say #1173 is an even worse problem than this issue, because this I can workaround (though not pretty), the other I cannot.

**Comment by defunctzombie** [comment]
@substack @zertosh ping. Without this, the `.external(bundle)` feature is not working. Is there a workaround or fix?

**Comment by zertosh** [comment]
Took a look at this. Since `bundle1` is added to `bundle2` via `external`, `bundle2` [waits](https://github.com/substack/node-browserify/blob/12.0.1/index.js#L247) until `bundle1` is consumed (i.e. `bundle1.bundle()` is called).

On the surface, it would make sense that when `bundle2.external(bundle1);` and `bundle1` hasn't bundled, then `bundle2` would call `bundle1.bundle()`. But, that seems really intrusive, especially since it's essentially dumping the output of `bundle1`.

@defunctzombie wrt to your repro case, this works:

```js
// adding and removing this line causes failure //
bundle2.external(bundle1);

// add this:
bundle1.bundle();

bundle2.bundle(function(err, src) {
    console.log(err, src);
});
```

Or, bundling `bundle2` once `bundle1` has started:

```js
bundle1.on('bundle', function() {
  bundle2.bundle(function(err, src) {
      console.log(err, src);
  });
});
bundle1.bundle(/***/);
```

**Comment by defunctzombie** [comment]
What will happen to bundle1 errors in the case of just calling bundle()
with no callback or capturing the result.

**Comment by zertosh** [comment]
Calling `bundle1.bundle()` w/o a callback or an `error` handler will generate an uncaught exception. But what's the use case for that?

**Comment by defunctzombie** [comment]
None, actually the opposite; just need to know how to prevent the uncaught
exception appropriately
