### ISSUE TITLE
Aliased dependencies are not passed to transform when added to bundle via .require or .add

### ISSUE THREAD

**Issue by MarkLeMerise** [browserify/browserify#1207]
> [Repo demonstrating this issue](https://github.com/bendrucker/browserify-shim-issue-152)

I noticed this issue when working with the [`browserify-shim`](https://github.com/thlorenz/browserify-shim) transform, and reported in thlorenz/browserify-shim#152.

If there is a `package.json` anywhere in the path of an alias defined in the `browser` field, it will be treated as if it came from `node_modules`, and thus not passed to the transform.

**Comment by garthk** [comment]
`*tumbleweeds*`
`*crickets*`

Did you come up with a workaround?

**Comment by MarkLeMerise** [comment]
In my particular workflow, I copied the aliased file to a temporary directory, ran Browserify, and then deleted the file. It was hacky, but it worked.
