### ISSUE TITLE
Node api created by the foundation

### ISSUE THREAD

**Issue by No9** [browserify/browserify#1314]
The node.js foundation has opened a repo to create a working group around the JSApi
https://github.com/nodejs/api
this is a good opportunity to improve the alignment  between the browserify implementation and server node by sharing tests and making the core spec more in tune with running node in non server environments.
hope some folks here find this useful

**Comment by caspervonb** [comment]
That WG looks like it's working towards a common javascript runtime API/ABI (C++), or am i missing something here?

**Comment by No9** [comment]
It seems to be both a low-level api and as JS API. 
I raised some points around building a browser-like implementation of node here
https://github.com/nodejs/api/issues/1 

The reply seems to be that sharing with the spec with browser based projects is of interest to that working group :)

**Comment by magicfish2007** [comment]
MAYBE  not only a low-level api and as JS API but also Nodejs api?
For that node rely on V8, and people shouldn't use current Node api(with V8 data struct) with a new JSApi in a native module(i.e. node add-on).
