### ISSUE TITLE
Question: Can you add variables to the outer closure generated by Browserify?

### ISSUE THREAD

**Issue by Ghazgkull** [browserify/browserify#1337]
Does Browserify provide any way to add variables to the top-most closure it generates?

I'd like to define a variable that's not global, but is visible to all my modules. The standard answer of "use requires(...)" doesn't work in my case because the variable's value isn't ready at the time the dependencies are processed. I really need a way to declare a variable in the closure that encompasses all my modules.

P.S. I posted this question to StackOverflow over a week ago but didn't get any answers. If you can answer this question, I'm happy to turn it into SO rep for you: http://stackoverflow.com/questions/31442804/add-a-variable-to-the-outer-closure-defined-by-browserify

**Comment by kentor** [comment]
How about exporting an object with one property that you can get and set?

**Comment by Ghazgkull** [comment]
Thanks for the reply. I do have a workaround in place, which involves a bit of boilerplate code at the top of each of my modules. If you're interested in the details and my workaround (it involves asynchronously loading a required library), I wrote it up here: http://stackoverflow.com/questions/31441185/how-to-use-my-own-version-of-jquery-with-browserified-modules

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant
