### ISSUE TITLE
Automatic creation of multiple bundles

### ISSUE THREAD

**Issue by bfred-it** [browserify/browserify#1346]
This is a feature request or a workflow question.

I have a hyper modular application. Its entry point is currently a file that imports all the features:

```
require('./feature-a');
require('./feature-b');
require('./feature-c');
```

I would like to know of a way to split this entry point into separate bundles. **The motive here is performance:** make each feature be available as soon as possible.

**Wrong solution 1:** I could simply create a bundle directly from each feature, but the problem is that they have shared dependencies; doing so would include the dependency in each file.

**Wrong solution 2:** Create a bundle for each, plus a bundle with common dependencies (with `factor-bundle`) and load it first. This sort of works, but the scripts can't be loaded with `async` so if `common.js` is large, a smaller `feature-d` still has to wait for it to load, even if it doesn't depend on it.

**Ideal solution:** create x bundles from the first file and make internal requires work like AMD. Instead of having a single, heavy `common.js`, the first 1-2 levels of dependencies are transformed into AMD requires and bundled into smart bundles:

e.g. if only `feature-b` requires `jquery` and `lodash`, make a single bundle with all the three.
e.g. if `feature-a` and `feature-c` require `kew` and `raf`, either bundle them together, or create a `a-c-common.js` file.

---

I know this sounds complex, but maybe someone already came up with a better solution. For now I've only manually created 2-4 bundles that have 0 shared dependencies (or they do… and load them multiple times)

**Comment by spikebrehm** [comment]
See projects like:

* `factor-bundle` (https://github.com/substack/factor-bundle)
* `partition-bundle` (https://github.com/arian/partition-bundle)

These are also referenced in the [Browserify Handbook](https://github.com/substack/browserify-handbook)
