### ISSUE TITLE
Cannot find module 'event-queue' for node-promise

### ISSUE THREAD

**Issue by hhkaos** [browserify/browserify#1348]
Hi,

I'm trying to use browserify to make [arc-node](https://www.npmjs.com/package/arc-node) work at the browser but I'm getting this error:

```
$ browserify index.js > bundle.js
Error: Cannot find module 'event-queue' from 'e:\Workspace\ArcNode\node_modules\node-promise'
```

Is it because node-promise is not browserify friendly or am I doing something wrong?

Thanks in advance

**Comment by goto-bus-stop** [comment]
> Is it because node-promise is not browserify friendly or am I doing something wrong?

the former. you can do `-x event-queue` to prevent node-promise from trying to require event-queue.
