### ISSUE TITLE
require of “pdf2png-mp” results in “Cannot read property 'split' of undefined” in bundle.js

### ISSUE THREAD

**Issue by AshokKumarPathak** [browserify/browserify#1416]
I am doing browserify of “pdf2png-mp”  npm module with following steps:
1. $ sudo npm install pdf2png-mp
2. $ browserify -r pdf2png-mp -o bundle.js
3. Created a html file that includes the following:

```
     <body>
      <script src="bundle.js"></script>
      <script> 
    var md = require('pdf2png-mp');
 </script>
    </body>
```

Actual Results:
“TypeError: Cannot read property 'split' of undefined” at bundle.js:667

var version = process.versions.node.split('.').map(function (value) {
  return parseInt(value, 10);
});

Please help!

**Comment by terinjokes** [comment]
The [process module](https://github.com/defunctzombie/node-process/blob/master/browser.js#L71) used by Browserify simply includes an empty object for versions. The documentation from nodejs.org is:

> A property exposing version strings of Node.js and its dependencies.

As we are not node I'm not sure what, if anything, would be reasonable to include. I'd recommend opening a ticket on the [process](https://github.com/defunctzombie/node-process/issues) module to see what they think.

In either case, `pdf2png-mp` requires the Ghostscript binary, which wouldn't be available in a browser.

**Comment by AshokKumarPathak** [comment]
Thanks, I have raised a ticket on the process module (https://github.com/defunctzombie/node-process/issues/52).

Yes pdf2png-mp require Ghostscript binary.

Do you know similar module which can convert pdf file to an image file without using Ghostscript. Since Ghostscript cannot be used in browser.

Thank You!

**Comment by bjoerge** [comment]
@AshokKumarPathak [pdf.js](https://mozilla.github.io/pdf.js/) can render a pdf file to a canvas element. You should then be able to use `<canvasElement>.toDataURL()` to grab the image url.

**Comment by AshokKumarPathak** [comment]
Thanks bjoerge, I trying to use pdf.js.

**Comment by AshokKumarPathak** [comment]
Thanks, pdf.js is working for me.
