### ISSUE TITLE
Buffer 3.5.0 broken (required by XMLHttpRequest shim)

### ISSUE THREAD

**Issue by Ryuno-Ki** [browserify/browserify#1418]
Today I ran into feross/buffer/issues/79 (Cannot set property length of [object Object]), when browserifying code, which made use of XMLHttpRequest.

(You'll need to run `npm test` on [my ajar clone](https://github.com/Ryuno-Ki/ajar/tree/mocha) after commenting line 2, where I require `xmlhttprequest`).

As stated there, the issue could be found on browserify-site as well. Please consider downgrading buffer import in [your package.json](https://github.com/substack/node-browserify/blob/b7cf5bef990a6823d14e2d437e15112aa6b3adfa/package.json#L28) until the issue is solved.

**Comment by TheSharpieOne** [comment]
This has been fixed in buffer 3.6.0 (feross/buffer#88).  Please consider upgrading buffer version in package.json.
