### ISSUE TITLE
npm command fails if basedir refers a location outside working directory

### ISSUE THREAD

**Issue by gdrouet** [browserify/browserify#1421]
This [application](https://github.com/my3D-Team/js-html-kanban) works fine when running `npm run build` command. The `package.json` file configures the following command to be executed:

> browserify --debug app/js/main.js  | exorcist app/bundle.js.map | uglifyjs -cm > app/bundle.js

If I modify this command to execute browserify with `basedir` option, it will continue to work until I specify a location outside the working directory (where the command is executed). I created branch to reproduce the issue [here](https://github.com/my3D-Team/js-html-kanban/tree/issue-basedir).
In this branch I just moved the `package.json` file in a sub directory called `nodeapp` and modified the command to be executed:

> browserify --debug ./app/js/main.js --basedir ../ | exorcist app/bundle.js.map | uglifyjs -cm > app/bundle.js

When I move to the `nodeapp` directory and execute `npm run build`, I obtain this mysterious error:

> Parsing file App.react.js: Unexpected token (50:20)

Seems in that case browserify does not rely on reactify to transform the file.

Any ideas?

**Comment by goto-bus-stop** [comment]
Transforms specified in package.json only apply to files in and below the directory the package.json file is in. In this case, app/js/main.js etc. do not have a package.json in a parent directory that specifies the reactify transform, so it's not added.
