### ISSUE TITLE
\ufeff character problem

### ISSUE THREAD

**Issue by FSou1** [browserify/browserify#1445]
I use browserify to bundle my *.js and *.html files into single bundle.js. I'm really confused about next character in my template:
![image](https://cloud.githubusercontent.com/assets/1132431/11342017/34ab677e-9216-11e5-9abd-5f111f4e819a.png)
I've checked it in bundle.js, here is:

``` javascript
function(e,t,n){t.exports="\ufeffhello"},{}
```

This is result of sourcemaps:
![image](https://cloud.githubusercontent.com/assets/1132431/11342167/ff0913a4-9216-11e5-9d98-d9460d5c7ed3.png)

I removed sourcemap creating, uglifying but this character still here.

I tried to change `html-browserify` to `stringify`, but the problem wasn't solved.

Here is notepadd++ content of fables.list.html file, special charactes: on, encoding: utf-8-bom, length 5:
![image](https://cloud.githubusercontent.com/assets/1132431/11342307/be43db46-9217-11e5-9e5d-00d7d2af4d6c.png)

That's my current gulp.task:

``` javascript
var gulp = require('gulp'),    
    browserify = require('browserify'),
    html = require('html-browserify'),
    source = require('vinyl-source-stream'),
    buffer = require('vinyl-buffer'),
    uglify = require('gulp-uglify'),
    sourcemaps = require('gulp-sourcemaps'),
    clean = require('gulp-clean');

gulp.task('browserify', function () {
    return browserify({ entries: 'client/app/js/app.module.js' })
        .transform(html)
        .bundle()
        .pipe(source('bundle.js'))
        .pipe(gulp.dest('client/dist/js'));
});
```

**Comment by FSou1** [comment]
Change encoding from `UTF-8 with signature` to `UTF-8 without signature` helped me. Is it my encoding problem only?

**Comment by yaycmyk** [comment]
Yeah, UFEFF is the UTF8 byte order mark, which a lot of tools have trouble parsing. I'd just use standard UTF8 encoding without it for compatibility reasons.

**Comment by goto-bus-stop** [comment]
yeah, recommend using utf-8 w/o signature--if anyone runs into this issue in the future please raise it with `html-browserify` or `stringify` maintainers. browserify strips the BOM character from the start of files but if a transform doesn't handle it correctly it can cause the BOM to appear somewhere in the middle of a file where browserify won't touch it.
