### ISSUE TITLE
Documentation should have API example that includes the source maps

### ISSUE THREAD

**Issue by metabench** [browserify/browserify#1470]
Currently, the API example is limited to:

```
var browserify = require('browserify');
var b = browserify();
b.add('./browser/main.js');
b.bundle().pipe(process.stdout);
```

It would be great to have an example that shows how source maps get included in the output. The documentation makes it clear how to do this from the command line, but not through the API.

If anyone can advise how to build using the API using source maps in this thread that would help too.

**Comment by substack** [comment]
```
var b = browserify({ debug: true })
```

**Comment by goto-bus-stop** [comment]
the readme mentions the `debug` option in the api documentation: https://github.com/browserify/browserify#browserifyfiles--opts
