### ISSUE TITLE
Enhancement: Output dependency list in makefile format

### ISSUE THREAD

**Issue by kasbah** [browserify/browserify#1477]
This would ease inter-operation with the [Ninja build system](https://ninja-build.org) and it's [depfiles](https://ninja-build.org/manual.html#_depfile). Currently I have to write horrible commands like below to get this inter-op (using [ninja-build-gen](https://github.com/jeanlauliac/ninja-build-gen)).

``` coffeescript
#browserify and put dependency list in $out.d in makefile format using
#relative paths
ninja.rule('browserify')
    .run("echo -n '$out: ' > $out.d 
          && browserify $in --list | sed 's!#{__dirname}/!!' | tr '\\n' ' ' >> $out.d 
          && browserify $in -o $out")
    .depfile('$out.d')
```

This could of course also be handled in Ninja but the author seems very hesitant to add anything not aimed at large C/C++ codebase compilation. Feel free to close if you don't think it's a needed feature for Browserify though.

**Comment by goto-bus-stop** [comment]
i think the `sed` solution you're already using is fine--i expect the use case is rare enough that it doesn't warrant special handling inside browserify itself, and a little format juggling is to be expected when using various different tools :)
