### ISSUE TITLE
Cannot find module './lib-cov/mocha'

### ISSUE THREAD

**Issue by dschinkel** [browserify/browserify#1502]
I'm getting the infamous Cannot find module './lib-cov/mocha' error when trying to run this command from the root of my node project:

browserify test/features/specs/companies-list-spec.js -o test.bundle.js

I've looked all over the net, and nothing really tells you a good way to resolve this problem.

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one with a reproduction if this is still relevant
