### ISSUE TITLE
Broswerify bundles but doesn't work

### ISSUE THREAD

**Issue by ghostropic** [browserify/browserify#1506]
Trying to use gulp and browserify to get dependencies.  To try it out I grabbed the jQuery npm module and required it and piped it through gulp and it creates a bundle.js which shows up attached in browser dev console and when I click the source in chrome dev tools it shows up like the code snippet below.  I'm wondering if the require wrapper is disabling jQuery somehow? because I am for sure getting a `Uncaught ReferenceError: $ is not defined` in the console.  I am including my bundle.js as a separate file right before my main js file just before the closing body tag.  Even if I try typing `jQuery` into the console I get `Uncaught ReferenceError: $ is not defined...`.  Pretty sure I just don't get it but addressing it here anyway because I just don't know what to do.

```
(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
/*!
 * jQuery JavaScript Library v2.2.0
 * http://jquery.com/
 *
 * Includes Sizzle.js
 * http://sizzlejs.com/
 *
 * Copyright jQuery Foundation and other contributors
 * Released under the MIT license
 * http://jquery.org/license
 *
 * Date: 2016-01-08T20:02Z
 */

(function( global, factory ) {

... cut out middle of jQuery because too long ...

return jQuery;
}));

},{}],2:[function(require,module,exports){
var jQuery = require("jquery");
},{"jquery":1}]},{},[2]);
```

**Comment by goto-bus-stop** [comment]
module variables are scoped to their function wrapper in browserify, so doing `var jQuery` inside a bundled module will not make `jQuery` available outside it. this way different modules can use the same variable names without accidentally overriding each other. to expose a variable globally, you have to do `window.jQuery = window.$ = require('jquery')`
