### ISSUE TITLE
Transform in package.json on symlinked modules not working in npm3

### ISSUE THREAD

**Issue by laurencedorman** [browserify/browserify#1512]
**Environment:** node@5.70 npm@3.75 browserify@13.0.0 babelify@7.2.0

Trying to build an app that worked with `npm@2` and `babelify@6` but having problems upgrading to `npm@3` and `babelify@7`. Allow me to try and explain the problem.
- In `app/node_modules` I have modules installed via `npm install` and local modules symlinked via `npm link`. 
- The local modules have browserify transforms specified in their `package.json` e.g -

``` json
...
  },
  "devDependencies": {
    "babel-preset-es2015": "^6.5.0",
    "babelify": "^7.2.0"
  },
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            "es2015"
          ]
        }
      ]
    ]
  }
...
```

Attempting to build I get error:

`"Browserify Error: Couldn't find preset "es2015" relative to directory"`

npm 3 has flattened out the dependency tree, so the `babel-preset-es2015` the symlinked module needs are in the `node_modules` of `app`. According to the explanation by @substack [here](https://github.com/substack/browserify-handbook#how-node_modules-works) and this example [here](https://github.com/maxogden/art-of-node/#how-require-works) browserify should walk up the tree from the symlinked module to `app` and check in the `node_modules` there, but it doesn't seem to be doing this. 

My directory layout looks like this:

```
~/projects
  |-- app
    |-- entry.js (this file can see babel-preset just fine)
    |-- node_modules
       |-- babel-preset-es2015
       |-- my-module (symlink pointing at ~/projects/modules-shared/my-module)
          |-- index.js (we want babelify to transform this file)
  |-- modules-shared
     |-- my-module
```

If I install `babel-preset-es2015` in the `modules-shared` folder, browserify finds the preset. 

I get the impression from looking through other issues that this sort of problem has come up before and has long been fixed, so I wonder why I have the problem now.

**Comment by ld0rman** [comment]
If I use the `paths` option supplied by browserify, and add the path to the top-level `node_modules` again, the symlinked modules manage to find their dependencies. At least, everything apart from the preset for babel, but I think that this is a problem with babel and I am opening an issue on their platform.

**Comment by scurker** [comment]
Just wanted to chime in on this since I'm running into a similar issue with symlinked modules. 

It's definitely an issue with browserify, more specifically module-deps. The path passed to the babelify transform is the realpath to the file, not the symlinked path, so babelify has no way of knowing where to look for plugins since it has no context of the source directory where the symlinked package is located.

**Comment by scurker** [comment]
With my structure, I was able to get a workaround, although not quite ideal.

```
project
|-- app
|  |-- entry.js
|-- node_modules
   |-- local_module/index.js (transforms correctly)
   |-- symlinked_module/index.js (resolves to realpath when passed to babelify)
```

Any plugins I'm using for transforms will potentially need to be both in the root project and `node_modules` directory of the symlinked package in order for babelify to apply the transforms correctly.

```
project
|-- app
|  |-- entry.js
|-- node_modules
   |-- babel-preset-2015
   |-- local_module/index.js
   |-- symlinked_module/index.js
      |-- node_modules
         |-- babel-preset-2015
```

Once the plugin is available under the symlinked module's location, browserify does transform correctly. It would be great if it could work out of the box with symlinked modules, but I realize it's probably a narrow case that could present some big issues.

**Comment by TehShrike** [comment]
Should this issue be [opened under module-deps](https://github.com/substack/module-deps/issues)?

**Comment by laurencedorman** [comment]
@bryantAXS for this case we decided that shipping uncompiled es6 code in this way was a code smell. Ideally you should be compiling es6 code to es5 in node modules. You can supply es6 code as well but only with a es5 fallback, and it’s better to use a more robust API like the ‘next’ field in the package.json or the .esm extension

**Comment by ljharb** [comment]
`.mjs` - i'm not aware of anybody using `.esm`.

**Comment by laurencedorman** [comment]
Yes thanks, I meant that @ljharb
