### ISSUE TITLE
Allow uncompressed packed code above / below source code in bundles

### ISSUE THREAD

**Issue by juliandoucette** [browserify/browserify#1520]
Some (including myself), would make the argument that it is unethical to include compressed code as part of a web page / application; especially without sourcemaps.
1. Since you do not compress source code by default when creating a bundle, can you not compress the packed code above / below source code by default too?
2. Can you add an API option and command line option to compress or not compress the code packed above / below source code?

**Comment by jmm** [comment]
> Some (including myself), would make the argument that it is unethical to include compressed code as part of a web page / application; especially without sourcemaps.

What? I'm curious what you mean, so please do make the argument. I've never heard that before. In any case, I would like there to be an easy way to produce bundles with unminified preludes for debugging. I think you can do that now semi-manually by passing `opts.prelude` / `opts.preludePath` for browser-pack, but I don't think there's a solution for the UMD prelude for `standalone`.

**Comment by juliandoucette** [comment]
"What? I'm curious what you mean, so please do make the argument. I've never heard that before."

Assuming you understand and agree with the 4 essential freedoms of free (as in freedom) software:

Freedom 0: The freedom to run the program for any purpose.
Freedom 1: The freedom to study how the program works, and change it to make it do what you wish.
Freedom 2: The freedom to redistribute copies so you can help your neighbor.
Freedom 3: The freedom to improve the program, and release your improvements (and modified versions in general) to the public, so that the whole community benefits.

Compressed/minified code is not compatible with Freedom 1 because one cannot study how the program works.

It is possible to compensate for this with source maps and proper labelling of software licences.

One might also reference [The JavaScript Trap](https://www.gnu.org/philosophy/javascript-trap.en.html) published by the free software foundation.

**Comment by jmm** [comment]
Thanks for the info. If you're uncomfortable shipping bundles with a minified prelude I recommend you check out the options I mentioned. You could also utilize that to prepend comments to your bundle.

FWIW I'm guessing this won't persuade enough people that unminified prelude should be the default.

**Comment by juliandoucette** [comment]
> FWIW I'm guessing this won't persuade enough people that unminified prelude should be the default.

I disagree with this point of view ideologically because I think the freedom of code is more important than how it looks when bundled. And I think I see where you are coming from -> if you think that the user wants to clearly see their bundled code without being distracted by or scrolling through the packed code around it. Therefore, I can see why you (and others) might not want to change the default.

However, shouldn't there (at least) be an option to include it uncompressed so that one does not have to include source maps and external links to distribute source code that respects the essential 4 freedoms of free software?

**Comment by goto-bus-stop** [comment]
you can do this by passing options

```js
var prelude = require.resolve('browser-pack/prelude')
browserify({
  prelude: fs.readFileSync(prelude, 'utf8'),
  preludePath: prelude
})
```

if you need the same for `--standalone` you'd have to write a custom umd wrapper instead of using the standalone option
