### ISSUE TITLE
List npm dependencies

### ISSUE THREAD

**Issue by orbatschow** [browserify/browserify#1521]
I have a question: 

I want to exclude all my libraries from my app bundle. So far so good, I have a configuration file, which keeps all needed libraries inside. My question is now: How can i get all node_module names, which i require in my sources from browserify, so that i can exclude them before i build the bundle ?
How can i achieve this with gulp ?

**Comment by goto-bus-stop** [comment]
you can use the `--no-bundle-external` flag on the cli or the `bundleExternal: false` option to the Node API to exclude all files from node_modules from the bundle.

you can also use `fs.readdir` on the node_modules folder to get a list of all installed module names.
