### ISSUE TITLE
Require context this

### ISSUE THREAD

**Issue by lbineau** [browserify/browserify#1525]
Hi,

I want to require the library [Detectizr](https://github.com/barisaydinoglu/Detectizr) that use the "this" as a the "window" object. I think that is not a good idea but anyway, is there a way to define a context in the require call ?

``` javascript
var lib = require('mylib', {context: window});
```

Thank you

**Comment by mderijcke** [comment]
Someone else had this problem before: http://stackoverflow.com/a/26595809

If you read the SO post you can see the person answering wrote a nice transform for this: https://www.npmjs.com/package/moduleify

**Comment by goto-bus-stop** [comment]
since browserify aims to do what node does, i think this is out of scope--that transform looks like a good option!
