### ISSUE TITLE
Not require jquery

### ISSUE THREAD

**Issue by webchaz** [browserify/browserify#1529]
Is it possible to have `$` available everywhere? Without explicitly having to call `var $ = require('jquery')` - It actually seems to be working "sometimes", but in some cases `$` is undefined.

**Comment by petr001** [comment]
global.$ = require("jquery")
or
window.$ = require("jquery")

**Comment by Redsandro** [comment]
Is it possible to have a module that is being required _think_ `$` is everywhere, but it does not actually end up in the broswer globals?

**Comment by goto-bus-stop** [comment]
> Is it possible to have a module that is being required think $ is everywhere, but it does not actually end up in the broswer globals?

you could use (or write) a browserify transform that adds `var $ = require('jquery')` at the top of each module that contains a `$`
