### ISSUE TITLE
Having an issue with 'browser' field

### ISSUE THREAD

**Issue by kgraves** [browserify/browserify#1530]
Here's my setup:
- node v5.0.0
- npm v3.3.6
- browserify v13.0.0

Here's my package.json

``` json
{
  "name": "emcee-craft",
  "version": "1.0.0",
  "main": "./lib/emcee-craft.js",
  "scripts": {
    "build": "browserify browser.js -o ./dist/app.js"
  },
  "dependencies": {
    "minecraft-data": "1.2.6",
    "underscore": "1.8.3"
  },
  "devDependencies": {
    "browserify": "13.0.0"
  }
}
```

my project structure is as follows:

```
- package.json
- browser.js
- lib/
    - emcee-craft.js
- dist/
    - index.html
    - app.js (browserify output)
```

I want `lib/emcee-craft.js` loaded when using node, and `browser.js` loaded when browserify-ing (which requires `lib/emcee-craft.js`).

When I specify `"browser": "browser.js"` in my package.json and build with browserify, `browser.js` is included in my browserify package, but `lib/emcee-craft.js` is not.
However, when I specify `"browser": { "browser.js": "browser.js" }` everything is included in the package, and I can run it in the browser without a problem.

I'm not really sure why the latter works and not the former; to me they seem like the same thing. I've read the [browser field section](https://github.com/substack/browserify-handbook#browser-field) of the browserify handbook, but didn't find any answers there. Is there anything that I'm missing?

**Comment by EvanCarroll** [comment]
> I want lib/emcee-craft.js loaded when using node, and browser.js loaded when browserify-ing (which requires lib/emcee-craft.js).

That's circular, read the spec on the [browser field](https://github.com/defunctzombie/package-browser-field-spec). It's a resolver shorthand.

    browser: { a: "b.js", c: "d" }

will resolve `require("a")` to `require("b")` and `require("c")` to `require("d")` when run in something that is building for a browser. You can resolve `lib/emcee-craft.js` to `browser.js` using this trick, but then you can't go back and include the real `lib/emcee-craft.js`. That's not what this feature is for.

**Comment by jmm** [comment]
@EvanCarroll I don't see that it's necessarily circular. If you had this it would be:

```js
// browser.js
require("./");
```

But not if you had:

```js
// browser.js
require("./lib/emcee-craft");
```

But the report doesn't show what's in `browser.js` or include a minimal reproduction.

@kgraves If this is still a problem, please provide a minimal reproduction that demonstrates it. If you need help getting started please see https://github.com/miniminirepro/browserify/tree/api. If it's no longer a problem, please close the issue. Thanks!

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant.
