### ISSUE TITLE
Error: Cannot find module 'node_modules/is-buffer/index.js' from ...

### ISSUE THREAD

**Issue by fanatid** [browserify/browserify#1531]
``` shell
$ cat buf.js 
module.exports = function (b) { return Buffer.isBuffer(b) }
$ npm i browserify
...
$ ./node_modules/.bin/browserify buf.js 
Error: Cannot find module 'node_modules/is-buffer/index.js' from '/home/kirill/tmp'
    at /home/kirill/tmp/node_modules/resolve/lib/async.js:46:17
    at process (/home/kirill/tmp/node_modules/resolve/lib/async.js:173:43)
    at ondir (/home/kirill/tmp/node_modules/resolve/lib/async.js:188:17)
    at load (/home/kirill/tmp/node_modules/resolve/lib/async.js:69:43)
    at onex (/home/kirill/tmp/node_modules/resolve/lib/async.js:92:31)
    at /home/kirill/tmp/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:82:15)
$ vim buf.js
$ cat buf.js
;(function () { new Buffer(0) })()
module.exports = function (b) { return Buffer.isBuffer(b) }
$ ./node_modules/.bin/browserify buf.js 
(function e(t,n,r){function s(o, ... // ok
```

Related: https://github.com/substack/node-browserify/issues/1228

**Comment by nazar-pc** [comment]
Any solution to this issue? `node_modules/is-buffer/index.js` is actually present in my case.

**Comment by kenberkeley** [comment]
Same issue
```
> browserify t.js > t.out.js

Error: Cannot find module '../../../../.1.1.5@is-buffer/index.js' from '/Users/kenberkeley/Desktop/tmp/test/node_modules/.1.0.2@core-util-is/lib'
    at /Users/kenberkeley/Desktop/tmp/test/node_modules/.1.1.7@resolve/lib/async.js:55:21
    at load (/Users/kenberkeley/Desktop/tmp/test/node_modules/.1.1.7@resolve/lib/async.js:69:43)
    at onex (/Users/kenberkeley/Desktop/tmp/test/node_modules/.1.1.7@resolve/lib/async.js:92:31)
    at /Users/kenberkeley/Desktop/tmp/test/node_modules/.1.1.7@resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/kenberkeley/.nvm/versions/node/v6.9.1/bin/node" "/Users/kenberkeley/.nvm/versions/node/v6.9.1/bin/npm" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! test@1.0.0 build: `browserify t.js > t.out.js`
```

**Comment by tianxiaofeng747** [comment]
I've had the same problem

**Comment by melkishengue** [comment]
Same problem here, does anyone did solve this issue ?

**Comment by nazar-pc** [comment]
My workaround was to write a script instead of using CLI. I'm calling browserify from gulpfile.js and it works correctly.

**Comment by studyinhub** [comment]
Same problem here, does anyone did solve this issue ?

**Comment by nazar-pc** [comment]
@studyinhub, make your own script and use it instead of Browserify CLI.

**Comment by kenberkeley** [comment]
@studyinhub 
According to @nazar-pc 
You can use `npx`

**Comment by goto-bus-stop** [comment]
It looks like the problem is that here, sometimes the resulting `relpath` value does not have a `./` in front: https://github.com/browserify/insert-module-globals/blob/master/index.js#L37

That results in output like `require('node_modules/is-buffer/index.js')`, which tries to find a module called "node_modules", instead of treating it as a plain file path.

**Comment by felixhao28** [comment]
I just met this issue today and it turned out that using an alternative npm ([cnpm](https://github.com/cnpm/cnpm/issues/225)) to be the culprit. cnpm handles modules folder differently with symlinks for faster installations, but it screws up the dynamic module resolving.

I am putting this info here because of the potential vulnerability of browserify when modules are managed differently.

**Comment by awwright** [comment]
I keep running into this if I try to install browserify in the same directory as the package I want to use it in.
If I install browserify in a separate directory, it works.
This is totally inexplicable.

**Comment by goto-bus-stop** [comment]
This should be fixed in insert-module-globals@7.0.2; do `npm update` to get it!

**Comment by Zeeech** [comment]
> I just met this issue today and it turned out that using an alternative npm ([cnpm](https://github.com/cnpm/cnpm/issues/225)) to be the culprit. cnpm handles modules folder differently with symlinks for faster installations, but it screws up the dynamic module resolving.
> 
> I am putting this info here because of the potential vulnerability of browserify when modules are managed differently.

Did you hava any solution about this？ cnpm handles modules folder differently with symlinks for faster installations, but it screws up the dynamic module resolving.

**Comment by felixhao28** [comment]
@Zeeech Don't use cnpm.

**Comment by Zeeech** [comment]
> @Zeeech Don't use cnpm.

Thx。I already find a great solution to use cnpm, just put follow option to your package.json.

```
"cnpm" :  {
  "mode" : "npm"
}
```

**Comment by MirFahad58** [comment]
Just do that => `npm install is-buffer --save`

**Comment by dreamingofcode** [comment]
TRY DELETING:
A.
1) yarn.lock
2)package-lock.json
3)node-modules
and reinstall with either yarn build or npm

B.
restart your local server
