### ISSUE TITLE
Avoid bundling specific modules with Browserify

### ISSUE THREAD

**Issue by IonicaBizau** [browserify/browserify#1532]
How can I tell Browserify that I want to `require` a specific module from another file (or an npm module) instead from the bundle file?

See my SO question: http://stackoverflow.com/q/36148298/1420197

**Comment by MellowMelon** [comment]
Have you tried `--external` instead of `--ignore`?

**Comment by goto-bus-stop** [comment]
Closing as the SO question was answered. `--external` does this.
