### ISSUE TITLE
I used babelify 7.2.0, but also report error

### ISSUE THREAD

**Issue by dongtong** [browserify/browserify#1536]
```
.transform("babelify", {presets: ["es2015", "stage-0", "stage-1", "stage-2", "stage-3"], plugins: ["add-module-exports", "transform-es2015-modules-umd"]})
```

report : 

ReferenceError: [BABEL] F:\workspace\example4\src\javascripts\components\alert
x\3.0.0\alert.js: Unknown option: direct.presets while parsing file: F:\works
pace\example4\src\javascripts\components\alert\3.0.0\alert.js

**Comment by mderijcke** [comment]
Have you tried opening an issue over at babelify? This sounds pretty babel specific, especially the `direct.presets` bit.

**Comment by goto-bus-stop** [comment]
This was most likely because of an old babelify version that didn't support presets. closing as not a browserify bug. thanks!
