### ISSUE TITLE
Execution order of global-transforms + cli transforms 

### ISSUE THREAD

**Issue by aristidesfl** [browserify/browserify#1548]
These scripts fail when I try to use `uglifyify` inline. If I add it to the global transforms it works.
Do the global transforms get executed after or before the transforms specified in the cli arguments?
Is there any other thing preventing this from working?

```
"scripts": {
  "dev": "globify 'src/js/*.coffee' --debug --watch --verbose --outfile 'src/js/*.js'",
  "build": "globify 'dist/js/*.coffee' --verbose -t uglifyify --outfile 'dist/js/*.js'",
  "build:content": "browserify 'dist/js/content.coffee' --verbose -t uglifyify --outfile 'dist/js/content.js'"
},
"browserify": {
  "transform": [
    "coffeeify",
    "partialify"
  ]
}
```

**Comment by goto-bus-stop** [comment]
transforms specified on the command line run before those specified in package.json. global transforms run after all other transforms.
