### ISSUE TITLE
--node option with using gulp

### ISSUE THREAD

**Issue by rico345100** [browserify/browserify#1557]
how to add --node option when using browserify with gulp? i spent hours and still finding answer. every try i did wasn't work.

like this:
`browserify('app.js', { node: true })`

if i execute node app with bundled by browserify, it always said:

> TypeError: global.XMLHttpRequest is not a function

**Comment by terinjokes** [comment]
This needs to be documented better, but the `--node` CLI flag is a wrapper around several of the other options, as can be seen here: https://github.com/substack/node-browserify/blob/071642ad9cbb44cb530d43edfac17c5077a9442c/bin/args.js#L67-L87

**Comment by EvanCarroll** [comment]
This is a bug, I may look at fixing this today. This bug was previously closed for unknown reasns here https://github.com/substack/node-browserify/issues/1472

**Comment by stevus** [comment]
@EvanCarroll awesome - thanks for looking into this.
