### ISSUE TITLE
'//@ sourceURL' and '//@ sourceMappingURL' are deprecated, please use '//# sourceURL=' and '//# sourceMappingURL=' instead.

### ISSUE THREAD

**Issue by Bondifrench** [browserify/browserify#1559]
I get these warnings (see screenshot below) using browserify in the console of Chrome developer tools:
![image](https://cloud.githubusercontent.com/assets/4905917/15196240/c4412530-180e-11e6-8897-8605bdf0f670.png)

When googling the error, I can see that `webpack` has had the same [issue](https://github.com/webpack/webpack/issues/91). I can not pinpoint where in `path` the error is, any clues?

**Comment by terinjokes** [comment]
Browserify switched to using "//#" back in [November 2013](https://github.com/substack/browser-pack/commit/31fed3c009ea75c3aaebd5a6e8fb7bcc38f86a34). Are you using a recent version of Browserify?

**Comment by Bondifrench** [comment]
Thanks for the quick answer, it seems one of my dependencies [browserify-server](https://github.com/Raynos/browserify-server/blob/master/package.json) is using an [older version of Browserify](https://github.com/Raynos/node-browserify/blob/master/package.json#L3) `1.17.3` not in sync with the `browserify main repo` which is currently at version `13.0.1` 

This dependency used a `register` function [see here](https://github.com/Raynos/browserify-server/blob/master/index.js#L27), which does not exist anymore in the newer version of Browserify, would you know what today's equivalent would be?

**Comment by terinjokes** [comment]
@Bondifrench Browserify 2.x was a big change. It looks like all of those can easily be replaced with browserify plugins (via `bundle.plugin()`) nowadays.
