### ISSUE TITLE
Cannot find module 'reactify'

### ISSUE THREAD

**Issue by darkowic** [browserify/browserify#1560]
Hello

I have installed globally ( in python virtualenv and nodeenv environment ) all node packages.
`NODE_PATH` system variable is set to node_modules in env. `require` works well and is finding modules. My problem is that I'm trying to run
`/usr/bin/env browserify --transform reactify`
which throws
`Cannot find module 'reactify' from '/some/local/path/where/runned/browserify'`
It seems like browserify cant find modules installed globally while transforming.
If I set full path to to reactify
`/usr/bin/env browserify --transform /some/path/node_modules/reactify`
it works well.

Does it should work like this?

**Comment by kaustubh-karkare** [comment]
I'm encountering the same problem.

**Comment by darkowic** [comment]
@kaustubh-karkare I solved the problem while ago. What I remember that there was some `node_modules` directory in some directory above my working directory. Ensure that you don't have `node_modules` dir in your home dir.

**Comment by jcubic** [comment]
I have the same problem but with babelify the option is `-g / --global-transform` but it's not working

**Comment by goto-bus-stop** [comment]
You should use a locally installed browserify and transform instead.

(`-g` is for transforms that apply to all modules including dependencies, so it's "global" in a different sense 🙂 )

**Comment by jcubic** [comment]
That make sens, but this is like a bug because documentation suggest to install browserify globaly but you can't use transformer that is installed globaly and you need to install them locally which make no sense since you install browserify globally so it would work outside of npm package and run like global binary. But it's not working so this sounds like a bug.

**Comment by ljharb** [comment]
Nothing should be installed globally. If the docs suggest that, they should be changed.

**Comment by jcubic** [comment]
See the README, it's like that from forever:

# install

With [npm](https://www.npmjs.com/) do:

```
npm install -g browserify
```

**Comment by ljharb** [comment]
Yes, in the olden days that was the best practice, but that has changed, and many packages and tutorials haven’t updated their docs. These should be updated as well.
