### ISSUE TITLE
Unifying CLI and API (constructor) options.

### ISSUE THREAD

**Issue by EvanCarroll** [browserify/browserify#1570]
Would you accept a patch that moved the CLI to [Commander.js](https://github.com/tj/commander.js/) (or [minimist](https://www.npmjs.com/package/minimist), [yargs](https://github.com/yargs/yargs), [dashdash](https://github.com/trentm/node-dashdash)), and that unified the logic behind processing local arguments with the CLI arguments? This will clear off stupid bugs like `node:true` in the API, and close out 

https://github.com/substack/node-browserify/issues/1472
https://github.com/substack/node-browserify/issues/1277
https://github.com/substack/node-browserify/issues/1540
https://github.com/substack/node-browserify/issues/1479
https://github.com/substack/node-browserify/issues/1557
https://github.com/substack/node-browserify/issues/1452

(there are a few more that we may argue it would have also clarified)

We have complex logic for the CLI arguments, and the API-constructor arguments and redundant documentation. This would simplify it. It would also make downstream bugs easier to solve rather than requiring a convoluted browserify configure that specifies all of the options for node.

https://github.com/kevinbeaty/any-promise/issues/23

**Comment by substack** [comment]
browserify uses [subarg](https://www.npmjs.com/package/subarg) which uses minimist. I would be open to an `opts.node` parameter in the API and a few other things like that, but I don't think that should warrant a breaking change where a small patch could do.

**Comment by EvanCarroll** [comment]
It doesn't have to be a breaking change from the users perspective. We just need to unify `args.js` with `index.js`. This should be done by whatever is processing the CLI options, they should be mapped into API options (where all the logic is). All of those frameworks do this fairly easily and permit one argument hash (for `Browserify(..options)`) to be validated in the same fashion.

**Comment by goto-bus-stop** [comment]
AFAICT the API now supports the same arguments as the CLI; the CLI only converts some things from strings to a format that the Node API is happy with. Please open a new issue if things are still missing.
