### ISSUE TITLE
A transform for nested imports?

### ISSUE THREAD

**Issue by trusktr** [browserify/browserify#1572]
@benjamin has enabled the following experiment in Meteor: 

https://www.reddit.com/r/javascript/comments/4m5f03/meteor_133_introduces_nested_import_statements_if/

The Meteor user-base is wide, so the experiment will be highly tested. It might be nice for webpack to have a import-nestify transform so that more people can experiment with the idea.

**Comment by goto-bus-stop** [comment]
Would be neat; closing this issue tho in hopes of making the browserify issue list a bit less daunting :)
