### ISSUE TITLE
how to exclude my appcode from jasmine specs

### ISSUE THREAD

**Issue by Liero** [browserify/browserify#1585]
my folder structure is

```
/src
   /components
      /App.tsx
      /HomePage.tsx
   /tests
      AppSpec.tsx
      HomePageSpec.tsx
   index.ts
```

src/index.ts is entry point to my application and src/tests/*_/_Spec.ts are entry points to my tests.

**I want to browserify my app and my tests, but I want to avoid compiling the app twice.**

On the output should be

```
/dist
   /app.js        //common app code
   /index.js      //app entry point
   /specs.js      //specs entry point
```

what is the recommended way to do it?

so far I have tried to use factor-bundle:

```
var bundler = browserify({ basedir: '.', debug: true });
bundler.add("./src/index.ts");
bundler.add("./src/tests/Spec1.ts");
bundler.add("./src/tests/Spec2.ts");
bundler.plugin(tsify); 
bundler.external(config.externalModules);
var entryStream = source("index.js");
var specStream = source("specs.js");
bundler.plugin('factor-bundle', { outputs: [entryStream, specStream ] });

var appStream = bundler.bundle()
    .pipe(source('app.js'));

merge(bundleStream, entryStream, testStream)
  pipe(gulp.dest(paths.distDir))
```

however, only Spec1 was bundled.

I also tried separate browserify bundle for specs where I tried to externamize App.tsx, but the appcode was still present in the spec bundle:

```
var bundler = browserify();
bundler.add("./src/tests/Spec1.ts");
bundler.add("./src/tests/Spec2.ts");
bundler.plugin(tsify);
bundler.external('./src/components/App.tsx'),
bundler.bundle()
    .pipe(source("spec.js"))
    .pipe(gulp.dest(paths.distDir));
```

**Comment by goto-bus-stop** [comment]
factor-bundle should be the right way, I think the reason that you only got Spec1 is because you provided 3 entry points but only 2 output streams:

```js
bundler.add("./src/index.ts");
bundler.add("./src/tests/Spec1.ts");
bundler.add("./src/tests/Spec2.ts");
bundler.plugin('factor-bundle', { outputs: [entryStream, specStream ] });
```

factor-bundle assumes one output stream for each entry point, so you'd need `[entryStream, specStream1, specStream2]` or a single entry point that requires all specs.

please open a new issue if that doesn't help & if you still need it
