### ISSUE TITLE
opts.paths isn't working on server side

### ISSUE THREAD

**Issue by grill2010** [browserify/browserify#1605]
Hi,

I use browserify for bundling my project on server side and client side . On the client side it seems everything is working fine but on the server side the opts.paths isn't working correctly. Look at my gulp broswerify config below:

```
gulp.task('scripts', ['settings-script'], () => {
  const b = browserify({
    entries: 'app/scripts/main.js',
    transform: babelify,
    debug: true,
    paths: ['./app/scripts'],
    bundleExternal: false,
    browserField: false
  }).external('settings/Settings');

  return b.bundle()
    .pipe(source('bundle.js'))
    .pipe($.plumber())
    .pipe(buffer())
    .pipe($.sourcemaps.init({loadMaps: true}))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/scripts'));
});
```

Has it something to do with #1586 ? Because I always have to use the relative path to require any file and the paths option seems to be ignored by browserify? Is there a way to avoid the relative paths on the server side?

**Comment by goto-bus-stop** [comment]
yeah, this looks like #1586, let's move it there
