### ISSUE TITLE
Gulp 4 process doesn't exit when browserify task finished.

### ISSUE THREAD

**Issue by roman0x58** [browserify/browserify#1606]
Hi there, have a problem with exiting from my browserify task when bundle have a plugin configuration, in my case it's watchify, I've found the similar issue with livereactload plugin and my workaround is same that explained here https://github.com/milankinen/livereactload/issues/90

**Comment by caseyhoward** [comment]
I have mine listening for 'end':

```js
.on('end', function() {
  done();
});
```

**Comment by goto-bus-stop** [comment]
This is expected with watchify; watchify doesn't end unless you explicitly tell it to using `b.close()`.
