### ISSUE TITLE
How to force standalone library (window.xxxxx) even in presence of AMD loaders?

### ISSUE THREAD

**Issue by ibc** [browserify/browserify#1639]
I'm developing a single JS file widget built with browserify. The idea is to place it in any website by means of a legacy `<script>` tag and let the website application use it via the global `window.mywidget`.

I've found a [website](http://configurator.mclaren.com/configuration/startConfiguration.do?profileName=COUPE570S) using [Dojo Toolkit](https://dojotoolkit.org/) in which my widget does not run at all. I've realized that it happens due to this check in the bundled fie:

``` js
if (typeof define==="function" && define.amd) { define([],f) }
```

I understand that the website application could use its own AMD loader to load and use my widget, but certainly it may not be the case and I still need `window.mywidget` to exist.

How to deal with this scenario?

**Comment by joe-sky** [comment]
The browserify's default standalone mode does not seem to be doing this. You can try this plugin:[standalonify](https://github.com/joe-sky/standalonify), it should be able to solve your needs. Even using the AMD loader, the global module object still exists.

**Comment by ibc** [comment]
Thanks, however I don't want to place all my devs in yet another `deps` field.

**Comment by joe-sky** [comment]
The `deps` field doesn't have to set values, [here is an example](https://github.com/joe-sky/nornj/blob/use_browserify/gulpfile.js). I don't know if I understand correctly?

**Comment by goto-bus-stop** [comment]
You can set the `window.mywidget` variable in your entry point:

```js
// entry.js
var mywidget = require('./mywidget')
module.exports = window.mywidget = mywidget
```

Then bundle `entry.js` with or without `--standalone`, either works.

**Comment by goto-bus-stop** [comment]
you can view it as a separate entry point file, that requires your library and exposes it on a global, rather than as a part of your library.

but you can also use the deumdify plugin, then you do not need to add any files: https://www.npmjs.com/package/deumdify

personally i don't think this use case is common enough to add another option to browserify.

**Comment by goto-bus-stop** [comment]
anyway I will keep #1073 open in case someone wants to submit a patch
