### ISSUE TITLE
detecting dynamically generated requirements

### ISSUE THREAD

**Issue by aaronharwood** [browserify/browserify#1645]
The following `index.js` code does not lead to browserify including the required package:

```
var dir = './lib/';
if (process.env.BUFFERMAKER_COVERAGE){
  dir = './lib-cov/';
}

module.exports = require(dir + 'BufferMaker');
```

**Comment by bjoerge** [comment]
Browserify can only detect static requires. See http://stackoverflow.com/questions/21642398/compiling-dynamically-required-modules-with-browserify

You can try:
```js
if (process.env.BUFFERMAKER_COVERAGE){
  module.exports = require('./lib-cov/BufferMaker');
} else {
  module.exports = require('./lib/BufferMaker');
}
```

You'd also need to use something like [envify](https://github.com/hughsk/envify) to pass environment variables to your bundle.
