### ISSUE TITLE
I just want to know, how can I use it with gulp?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [browserify/browserify#1648]
**I just want to know, how can I use it with gulp?**

**Anybody can help?**

**Comment by joe-sky** [comment]
You can take a look at the [official document](https://github.com/gulpjs/gulp/blob/master/docs/recipes/README.md) of the `gulp`. Here's a [more complete example](https://github.com/callemall/material-ui-browserify-gulp-example?files=1).
