### ISSUE TITLE
Cannot find module when split up bundles

### ISSUE THREAD

**Issue by AnnieCyl** [browserify/browserify#1675]
I came into this problem when I try to split up bundles.

First, I  create a bundle named `moduleA`:
`browserify -r ./moudule-a.js:moduleA -o ./bundle/module-a.js`

Then I create another bundle which requires `moduleA` inside:
`browserify -x ./bundle/module-a.js -r ./module-b:moduleB -o ./bundle/module-b.js`

And I got this error: 
`Cannot find module 'moduleA'`

I don't know where I did wrong. Any help?

**Comment by casr** [comment]
If `./module-b.js` looks like:

```js
var a = require('moduleA')
// ...
```

Then you’ll need to exclude it by its module name and not by its filename:

`browserify -x moduleA -r ./module-b:moduleB -o ./bundle/module-b.js`
