### ISSUE TITLE
Tree-shaking and destructured require optimizations

### ISSUE THREAD

**Issue by stevenvachon** [browserify/browserify#1692]
It'd be great if:
```js
const {normalize:normalizePath} = require('path');
```
…and perhaps also:
```js
var normalizePath = require('path').normalize;
```
…would behave like:
```js
import {normalize as normalizePath} from 'path';
```
…in that it would only bundle `normalize()` and anything required for it to run.

**Comment by MellowMelon** [comment]
That would be the ES6 feature tree-shaking. Guaranteeing that tree-shaking is a correct optimization requires static imports and exports, as provided by the ES6 syntax. The nodeJS module system, which browserify's purpose is to emulate, makes it possible to dynamically change one module's exports from inside any other module, since each exports is just another mutable object.

If you want this feature, it would be best to write your code using the ES6 import and export keywords. Then [rollupify](https://github.com/nolanlawson/rollupify) does what you want. (At least it claims to. I have not used it before.)

**Comment by stevenvachon** [comment]
Tree-shaking has existed longer than ES modules. The first I'd heard of it was [jslim](https://github.com/zgrossbart/jslim).

**Comment by joepie91** [comment]
> Guaranteeing that tree-shaking is a correct optimization requires static imports and exports, as provided by the ES modules syntax. The nodeJS module system, which browserify's purpose is to emulate, makes it possible to dynamically change one module's exports from inside any other module, since each exports is just another mutable object.

There is no reason you can't implement tree-shaking using CommonJS/Node.js modules, so long as the `module.exports` in said modules is defined statically and at the top level. This gives you the exact same coverage as ES Module syntax does, and you can simply bail out when there's any indication that `module.exports` is modified from anywhere else within the file.

It's also a bad idea to be using `import`/`export` today (assuming that ES Modules are desirable over CommonJS in the first place), given that the loader specification isn't completed yet, and therefore it's flat-out *not possible* to have a correct implementation today.

**Comment by MellowMelon** [comment]
Indeed, tree-shaking can exist in CommonJS module syntax, or even in ordinary javascript. That bail-out logic would be somewhat involved though. For example, the linked library jslim admits that you can break it by using eval. These are the kinds of things that led to the ES modules spec defining new keywords that could be detected during parsing. I stand by my use of the word "guarantee", but I do admit that in 99% of cases it would work just fine.

While I am no expert, last I checked the ES modules spec had two parts, the declarative import/export syntax and the programmatic loader API. As you said, the latter is still being worked on. The former has been spec'd and finalized, so using import and export with a tool like rollup is much more likely to have compatibility issues with things today than things tomorrow.

All that said, this feature could be obtained via a transform or plugin, so if it happens that's probably the form it would take. As far as I know it does not exist yet. Maybe it would be quick to write via piping into rollupify?

**Comment by ahdinosaur** [comment]
i've been wondering if this is possible as a transform on top of [`rollupify`](https://github.com/nolanlawson/rollupify) and [`rollup-plugin-commomjs`](https://github.com/rollup/rollup-plugin-commonjs), but the lack of tree-shaking has never been a barrier to anything i want to do, so haven't bothered.

**Comment by goto-bus-stop** [comment]
https://www.npmjs.com/package/common-shakeify does this, through https://www.npmjs.com/package/common-shake!
