### ISSUE TITLE
--no-browser-field breaks transforms

### ISSUE THREAD

**Issue by nazar-pc** [browserify/browserify#1693]
Using `aliasify` transform alongside with `--no-browser-field` results in output like following:
```
node_modules/.bin/browserify lib/index.js --standalone mammoth --no-browser-field --transform aliasify -p browserify-prepend-licenses > mammoth.browser.js
Error: ENOENT: no such file or directory, lstat '/***/mammoth.js/path'
makefile:12: recipe for target 'mammoth.browser.js' failed
make: *** [mammoth.browser.js] Error 1
```

Here is the commit where I'm switching from using `browser` key in `package.json` to `aliasify`: https://github.com/nazar-pc/mammoth.js/commit/d2e0cf48fa8416b8a60518d1796334e69aa42249

If you just remove `--no-browser-field` key it works, but doesn't make sense, since `browser` key is already useless for Browserify.

**Comment by goto-bus-stop** [comment]
Hmm, --no-browser-field switches the module path resolution module from browser-resolve to just resolve, which also removes browser-resolve's knowledge of builtin shims. when resolving core modules like `path`, the resolve module just returns the name. browserify then tries to `fs.realpath` that name which of course does not make sense. i agree we should probably still use the shims even when --no-browser-field is passed; people who want to exclude the shims can use the --no-builtins flag.

this is the same problem as reported in https://github.com/browserify/browserify/issues/1654, moving there!
