### ISSUE TITLE
es6-promise error

### ISSUE THREAD

**Issue by TheBrokenRail** [browserify/browserify#1699]
Error: Cannot find module 'es6-promise' from 'C:\Users\<User Name>\Downloads\Browserify\node_modules\sumchecker'

**Comment by kovirolik** [comment]
Did you had installed es6-promise ?
https://github.com/stefanpenner/es6-promise

**Comment by goto-bus-stop** [comment]
hi @TheBrokenRail, is this still an issue for you?
