### ISSUE TITLE
Feature Request:  Emit 'end' event

### ISSUE THREAD

**Issue by FranciscoG** [browserify/browserify#1705]
Just a simple request to emit an 'end' event when using it in a script. 

```javascript
b.on('end', function(){
  // do something after browserify is done
});
```

**Comment by FranciscoG** [comment]
thanks for responding! Those 2 options are both very viable.  I ended up finding a solution right after I posted.

I wanted an end event so I can use Promises and I ended up doing something like this below.  I was already writing using **fs.createWriteStream** and I know that returns a stream with events so I was using that.  Not sure if this is the best way but it works so :man_shrugging: 

```
var b = browserify(options);

var mainFile = fs.createWriteStream('./myScript.js', 'utf8');

b.transform(babelify, {presets: ["es2015"]})
  .bundle()
  .pipe(mainFile);

return new Promise(function (resolve, reject){
    mainFile.on('finish', function(){
      resolve();
    });
    b.on('error', function(err) { reject(err); });
    mainFile.on('error', function(err){
      reject(err);
    });
  }); 

```

**Comment by goto-bus-stop** [comment]
IMO using the 'end' event on the `bundle()` stream is the way to go here, but happy to have a PR that also emits it on the browserify instance if someone disagrees.
