### ISSUE TITLE
Using require() API can cause process to hang

### ISSUE THREAD

**Issue by ste2425** [browserify/browserify#1707]
When creating a bundle through the Node API should you provide `require` with a path that will not resolve the error event will be invoked put the process will not end.

Should you `require()` in that exact same invalid path in a module, not using the `browserify().require()` API the exact same error event will but thrown, but this time the process will end.

I would have expected in both scenarios the error to be fired but then the process to end?

So if i have an `input.js` of:
```javascript
'use strict'

require('myModule');
```
And run this 
```javascript
browserify()
    .add('./input.js')
    .require('./some/invalid/path', {
        expose: 'myModule'
    })
    .bundle()
    .on('error', (e) => {
        // Fires
    });
```
it will error but the node process will never end.

However if i remove the `require()` call and instead have this in my `index.js` it will also error but the process wont hang.
```javascript
'use strict'

require('./some/invalid/path');
```

I've worked around it by manually asserting that the path exists before giving it to Browserify, However that isn't entirely ideal in the long run.

I can reproduce this on the latest `14.1.0` version.

**Comment by goto-bus-stop** [comment]
I can't reproduce this anymore; please open a new issue if it is still a problem. Thanks!
