### ISSUE TITLE
Only use specific builtins ?

### ISSUE THREAD

**Issue by giann** [browserify/browserify#1719]
Is it possible to only load a specific builtin ? (namely assert)

**Comment by goto-bus-stop** [comment]
You can specify an array of builtins to load using the Node API. e.g. with an example file `entry.js`:

```js
var assert = require('assert')
var events = require('events')
```

You can only include `assert` like so:

```js
var browserify = require('browserify')
browserify('./entry.js', {
  builtins: ['assert']
})
b.bundle().pipe(process.stdout)
```

On the command line you can do something similar using the `--exclude` option:

```bash
browserify ./entry.js --exclude events
```

Is that what you wanted to do?
