### ISSUE TITLE
--node equivalent for opts

### ISSUE THREAD

**Issue by mindvox** [browserify/browserify#1726]
Hiya,
I'm using this with Grunt and getting the `ReferenceError: window is not defined` which to avoid you use `--node` flag from the command-line.

How can I pass this or similar configuration to `node-browserify`?

**Comment by gwicksted** [comment]
`--node` is an alias for `--no-builtins`, `--no-commondir`, and sets `--insert-global-vars`
    to just `"__filename,__dirname"` so:

```javascript
{
    builtins: [],
    insertGlobals: [ "__filename", "__dirname" ],
    commondir: false
}
```

**Comment by goto-bus-stop** [comment]
16.1.0 adds a `node: true` option to the API!
