### ISSUE TITLE
Path must be a string

### ISSUE THREAD

**Issue by krazyjakee** [browserify/browserify#1730]
I am trying to compile this file: https://github.com/rkit/react-select2-wrapper/blob/master/src/components/Select2.js

With this code:
```javascript
var b = browserify(filePath, { // File path is valid. Double and triple checked.
        transform: ["reactify", { es6: true }]
      })
      b.transform("reactify")
      b.on('error', console.error)
      b.bundle((err, buff) => {
        if(err){ return console.log(err) }
        res.send(buff.toString())
      })
```

But I get:
```
{ TypeError: Path must be a string.
    at resolve (/Users/user/WebApp/node_modules/resolve/lib/async.js:15:19)
    at nr (/Users/user/WebApp/node_modules/module-deps/index.js:282:24)
    at /Users/user/WebApp/node_modules/resolve/lib/async.js:17:13
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

I am trying to compile jsx files and output the browser-ready code to a variable. Any help/advice would be appreciate.

**Comment by goto-bus-stop** [comment]
This seems to happen because you're adding the `reactify` transform twice. Not sure why it's throwing that specific error then yet.

**Comment by goto-bus-stop** [comment]
Oops, misread.

```js
transform: ["reactify", { es6: true }]
```

`transform` can receive an array of transforms, but this is defining a single transform with options. Browserify interprets this as an array of transforms, `reactify` and `{ es6: true }`. To fix, use:

```js
transform: [
  ['reactify', { es6: true }]
]
```

But also, add the reactify transform just once :)
