### ISSUE TITLE
issue with private modules tarting with @ / using --node

### ISSUE THREAD

**Issue by egandro** [browserify/browserify#1735]
Hello,

in my browsified (--node) file, I'll have issues with modules starting with "@"

According to NPM I use

`
 @mystuff/lib1 and @mystuff/lib1
`

In the final index.js I'll get a "can't require" error when using this names. However when I use
"mystuff_lib" everything is fine.

**Comment by goto-bus-stop** [comment]
it seems to work fine here; if this is still an issue can you provide a snippet that shows the problem?
