### ISSUE TITLE
Include logo and add license

### ISSUE THREAD

**Issue by bastien-roucaries** [browserify/browserify#1737]
Hi,

Could you add the logo as png and svg and license it ?

It is needed for debian

**Comment by goto-bus-stop** [comment]
https://github.com/browserify/browserify/commit/13e9d80f5a9e1ce32a98c73a802dd95d4a22ffbe
https://github.com/browserify/browserify/commit/38141f1ed6fc481704abcf9d76f1b3b2e65d2d00
