### ISSUE TITLE
 Error: Cannot find module 'envify' from spark-js-sdk

### ISSUE THREAD

**Issue by jacqljl** [browserify/browserify#1738]
Hi,

I  tried to manage spark js sdk

https://github.com/ciscospark/spark-js-sdk

and failed in step : browserify index.js > bundle.js

npm install ciscospark
npm install -g browserify
echo "window.ciscospark = require(`ciscospark`)" > ./index.js
browserify index.js > bundle.js

Error is following :

browserify index.js > bundle.js   Error: Cannot find module 'envify' from '/home/users/ljlevy/NodeScripts/spark-js-sdk'
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:48:31
    at processDirs (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:182:39)
    at ondir (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:197:13)
    at load (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:80:43)
    at onex (/usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:105:17)
    at /usr/lib/node_modules/browserify/node_modules/resolve/lib/async.js:26:73
    at FSReqWrap.oncomplete (fs.js:123:15)

npm -v
   3.10.10
node -v
   v6.11.0

However i can check envify is correclty installed 

 npm install -g envify
/usr/bin/envify -> /usr/lib/node_modules/envify/bin/envify
/usr/lib
`-- envify@4.0.0
  +-- esprima@3.1.3
  `-- through@2.3.8

i am on Docker on linux.

What is the root cause ?

thanks

Regards

**Comment by casr** [comment]
Does this fail outside Docker? Also try preferring local `browserify` over a globally installed version.

I tried to reproduce with (but had no problems):
```
 ❯ node --version
v6.11.1

 ❯ npm --version
3.10.10

 ❯ echo {} > package.json

 ❯ npm install -D -E browserify; npm install -S -E ciscospark

 ❯ cat package.json
{
  "devDependencies": {
    "browserify": "14.4.0"
  },
  "dependencies": {
    "ciscospark": "1.10.4"
  }
}

# Note: I added single quotes around ciscopark.
 ❯ echo "window.ciscospark = require('ciscospark')" > ./index.js

 ❯ export PATH=$(npm bin):$PATH

 ❯ browserify index.js > bundle.js
```

**Comment by goto-bus-stop** [comment]
it looks like you are running `browserify` from inside the https://github.com/ciscospark/spark-js-sdk repository, which causes browserify to pick up on spark-js-sdk's package.json config. you should build your own code in a different folder with your own package.json (or with no package.json).

browserify resolves transforms relative to the file being built, not globally. use `npm install envify` to install envify locally in your project folder, then it will resolve correctly.
