### ISSUE TITLE
Support pnpm-style module installation

### ISSUE THREAD

**Issue by kiranjholla** [browserify/browserify#1739]
Would it be possible to help resolve the issues faced when running browserify with node modules installed using pnpm?

Please take a look at [https://github.com/pnpm/pnpm/issues/795](https://github.com/pnpm/pnpm/issues/795) for details of an issue being faced with browserify when the modules are installed using pnpm.

Maintainer of pnpm believes browserify isn't resolving the modules the way node would.

**Comment by goto-bus-stop** [comment]
This should be fixed in v16—apologies for the long wait!
