### ISSUE TITLE
How to apply a transform after the ones defined in package.json?

### ISSUE THREAD

**Issue by oztune** [browserify/browserify#1763]
I'm trying to create a tool that runs browserify on a project, respecting its local browserify settings, but at the end checks that all `require()` paths are using the correct letter-casing (since my OS is case insensitive, and my servers aren't).

Browserify always applies the transforms defined in the `package.json` closest to the file it's processing _after_ the transforms defined programatically in `bundle.transform(...)`

I need to apply the `package.json` transforms _before_ the ones at the root. I looked through the codebase and can't find a way to do it. Am I missing something?

**This is what I'd like to be able to do:**

Let's pretend I have a project with this package.json:
```
// /path/to/my/project/package.json
{
  "browserify": {
    "transform": ["babelify"]
  }
}
```

And I run browserify like this, using the JS API:

```
const bundle = browserify()
bundle.add('/path/to/my/project/index.js')
bundle.transform(ensureRequireCallsUseCorrectCasing)
```

As it stands, the `ensureRequireCallsUseCorrectCasing` transform will run _before_ the `babelify` transform, which will fail because `import` statements haven't been turned into `require` yet.

How can I make `bundle.transform(ensureRequireCallsUseCorrectCasing)` run _after_ the `babelify` transform in this case?

**Comment by goto-bus-stop** [comment]
I don't think that's possible, but as a workaround you could write your transform as a plugin that hooks into the pipeline after all transforms have run.

```js
var through = require('through2')

module.exports = function transformLast (b, opts) {
  // Add to the end of the `deps` step, after module-deps has run all transforms
  b.pipeline.get('deps').push(through.obj(onrow))

  function onrow (row, enc, next) {
    RUN_TRANSFORM(row.source, function (err, transformedSource) {
      if (err) return next(err)
      row.source = transformedSource
      next(null, row)
    })
  }
}
```

Where `RUN_TRANSFORM` is a function that runs your transform and calls the provided callback with `(error, transformedSource)` when done. `row.source` is a string containing the file's source code.

**Comment by oztune** [comment]
@goto-bus-stop Thank you! I will try that 👍

**Comment by oztune** [comment]
I can confirm it works well. Thanks again!
