### ISSUE TITLE
Is it possible to have multiple entries but only run ONE?

### ISSUE THREAD

**Issue by tolmasky** [browserify/browserify#1766]
I have a browserify setup with two entries: entries["./file-1", "./file-2"]. Currently browserify generates a bundle where both these files are being run (auto-required). I'd like only ONE of the two to run on its own.

**Comment by goto-bus-stop** [comment]
Using the b.require method or the -r flag on the CLI will include the specified module in the bundle but not auto run it. Does that work for you?

**Comment by tolmasky** [comment]
Perfect, thank you.
