### ISSUE TITLE
browserify running transforms specified by child dependency unexpectedly

### ISSUE THREAD

**Issue by cdaringe** [browserify/browserify#1768]
# problem

repost from quiet SO post: https://stackoverflow.com/questions/46637231/browserify-runs-transforms-on-dependency-that-has-already-been-transformed

on `browserify`, bify is trying to run a child's transforms which is unexpected--the lib has already been built.

# reproduce

https://github.com/cdaringe/browserify-come-on-dawg

**Comment by goto-bus-stop** [comment]
i'm afraid that's [intended behaviour](https://github.com/browserify/browserify#browserifytransform). the `card` module is using the `browserify.transform` key incorrectly. packages should only specify it in their package.json if transforms should be run by the consumer.

**Comment by cdaringe** [comment]
Ya I think you're right.  Thx!
