### ISSUE TITLE
Error: "ETXTBSY: text file is busy, rename ..."

### ISSUE THREAD

**Issue by moszeed** [browserify/browserify#1772]
Hi,
with Version 14.x of Browserify i get the following Error:
```
Error: ETXTBSY: text file is busy, rename './dist/js/app.js.tmp-browserify-37022627279882813767' -> './dist/js/app.js'
```

Browserify is running inside a Virtual-Machine and Docker, 
the .js files are in a SharedFolder and getting sync with Host. 

is there a way to deactivate the creation of the .tmp file or change the folder where these .tmp files are created (so i can move them to a non sharedFolder) ?

Thank you

**Comment by goto-bus-stop** [comment]
if you don't need the `.tmp` file you can use the `>` operator instead of `-o`

```
browserify app.js > dist/js/app.js
```

would that work? i think it'd be best not to add options for a super small feature like the `.tmp` files.

**Comment by moszeed** [comment]
yes, that`s a solution that works ...
why did i not see this 🙈 ... shame on me ...

thx
