### ISSUE TITLE
-r needs a ./ before path name

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [browserify/browserify#1774]
`browserify -r try_require.js ` fails with:
```
Error: Cannot find module 'try_require.js' from '/Users/williamrusnack/Documents/form_database'
```

Which is a very unclear statement of needing a `./` before the file name because this works:
`browserify -r ./try_require.js`

Preferably, a local file name will work with the -r flag without the ./
If that is too hard, a better error stating the need for the ./

**Comment by casr** [comment]
In case it is confusing, `-r` follows the the same thing that you would put inside of a `require` call.

**Comment by BebeSparkelSparkel** [comment]
Helpful if that were in the docs!

**Comment by goto-bus-stop** [comment]
https://github.com/browserify/browserify#brequirefile-opts sort of mentions this, but yes it could be useful to mention it directly in the `-r` documentation as well.
