### ISSUE TITLE
How browserify resolves package.json `style` attribute ?

### ISSUE THREAD

**Issue by ZhouHansen** [browserify/browserify#1778]
A snip of `tachyons` package.json:
```json
{
  "style": "css/tachyons.min.css",
  "main": "css/tachyons.css"
}
```

[browserify/resolve](https://github.com/browserify/resolve) only resolve path by `main` attribute of `package.json`, check its [core](https://github.com/browserify/resolve/blob/master/lib/async.js#L157)

But `browserify` pass path `my-absolute-path.../css/tachyons.min.css` as `filename` argument to css transform `sheetify`. That path  which only can be resolved through `style` attribute of `package.json` . But there is nothing prove browserify can do it.

**Comment by goto-bus-stop** [comment]
sheetify resolves CSS file names using style-resolve https://www.npmjs.com/package/style-resolve. Browserify only resolves arguments to require

**Comment by ZhouHansen** [comment]
A snip of sheetify:

```javascript
module.exports = sheetify

function sheetify (src, filename, options, done) {
  console.log(filename) 
  // result out 'my-absolute-path.../css/tachyons.min.css', 
  // here's nothing deal with style-resolve now
  // ...
}
```

Why the filename browserify pass to sheetify is `tachyons.min.css` rather than `tachyons.css`.

**Comment by goto-bus-stop** [comment]
Are you using the sheetify transform? It calls sheetify's index.js with the path already resolved



On 1 December 2017 08:26:50 CET, "周汉成" <notifications@github.com> wrote:
>A snip of sheetify:
>
>```javascript
>module.exports = sheetify
>
>function sheetify (src, filename, options, done) {
>  console.log(filename) 
>  // result out 'my-absolute-path.../css/tachyons.min.css', 
>  // here's nothing deal with style-resolve now
>  // ...
>}
>```
>
>Why the filename browserify pass to sheetify is `tachyons.min.css`
>rather than `tachyons.css`. 
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/browserify/browserify/issues/1778#issuecomment-348421858

-- 
Sent from mobile. Please excuse my brevity.

**Comment by ZhouHansen** [comment]
I am using it. So I want to know why the resolved result is `tachyons.min.css` rather than `tachyons.css`. Even in `tachyons`'s package.json, the `main` attribute is 'css/tachyons.css'

**Comment by goto-bus-stop** [comment]
Sheetify transform uses style-resolve to resolve the name so it's looking at the style property in package.json

**Comment by ZhouHansen** [comment]
I replace `style-resolve` by `resolve`, then the result is the same, there's nothing dealing with `style-resolve`

**Comment by goto-bus-stop** [comment]
how did you replace it? i don't understand, browserify doesn't look at and doesn't know about the style property and it doesn't deal with arguments to `sheetify`. the sheetify transform resolves the `style` property here: https://github.com/stackcss/sheetify/blob/2b5722aa7d77b8cb78644177d6308c848cc27991/transform.js#L112

**Comment by ZhouHansen** [comment]
soga, thanks a lot!
