### ISSUE TITLE
Packages/paths in backticks (`) are ignored

### ISSUE THREAD

**Issue by TehShrike** [browserify/browserify#1782]
Browserify resolves `tape` correctly here:

```js
const test = require('tape')
```

but not here:

```js
const test = require(`tape`)
```

This differs from node's behavior.

---

Are you open to having this fixed?  I'm willing to add tests and write the patch.

## Context

I started using an eslint autoformat script with `quotes` set to `backtick`, so all of my strings are backtick-enclosed nowadays.  (See also: https://ponyfoo.com/articles/template-literals-strictly-better-strings )

**Comment by goto-bus-stop** [comment]
Yeah, I think this would make sense!

**Comment by TehShrike** [comment]
Once https://github.com/browserify/detective/pull/74 is merged and released, I'll update https://github.com/browserify/module-deps/pull/136 with the version bump, and then once that is merged and released, I'll update https://github.com/browserify/browserify/pull/1785

**Comment by TehShrike** [comment]
Sweet!  Should I update the changelog so that a new release can go out?
