### ISSUE TITLE
yield tests don't pass in node 8 or 9

### ISSUE THREAD

**Issue by TehShrike** [browserify/browserify#1784]
Experienced locally with node 9, reproduced in #1783

**Comment by bcomnes** [comment]
Tests pass if you remove the transform.  Can we do that?

**Comment by TehShrike** [comment]
Only if we stop testing on node 0.10 and 0.12, I would bet.

Can we stop supporting those versions of node?  0.12 has been end-of-life for a year now.

Related: https://github.com/browserify/browserify/pull/1785#issuecomment-354894275

**Comment by goto-bus-stop** [comment]
removed in https://github.com/browserify/browserify/commit/183162f84fcf8789f02b24c82d20ae3a13baf14b

**Comment by TehShrike** [comment]
And node 0.10 and 0.12 were dropped in e8dbe6c8a7ffd88863ec8db3d6bfa51976be8c38.  Rockin'.

**Comment by bcomnes** [comment]
Module deps also dropped 0.12 support so we should update that as well before doing a release

**Comment by TehShrike** [comment]
There wasn't any version specified in package.json yet, so I opened this PR https://github.com/browserify/browserify/pull/1793
