### ISSUE TITLE
Invalid repository URL in package.json.

### ISSUE THREAD

**Issue by darkurse** [browserify/browserify#1786]
Hi,

I cannot get browserify as a dependency for my project and it might be due to the recent repo name/url change :

Package.json
```
{
 ...
 "repository": {
    "type": "git",
    "url": "http://github.com/substack/node-browserify.git"
  },
 ...
}
```

I think that url changed to `"url": "http://github.com/browserify/browserify.git"` should fix it

**Comment by goto-bus-stop** [comment]
npm doesn't use that URL when installing (npm packages are downloaded from npm registry servers) so I don't think it will fix your problem. we should update it anyway tho!
