### ISSUE TITLE
"Initialize" transform once before any files are processed?

### ISSUE THREAD

**Issue by RedHatter** [browserify/browserify#1789]
I'm writing a transform that extracts content from files based on a regex and appends it into a file. It works great with one small caveat. I need to delete the file before each run so as not to keep appending on each build. Is there anyway I can run some code when the build starts?

    let through = require('through2')
    let fs = require('fs')

    function extract (file, options) {
      return through(function (buf, enc, next) {
        let contents = buf.toString('utf8')
          .replace(options.regex, function () {
            fs.appendFile(options.file, arguments[options.capture || 0],
              err => { if (err) throw err })

            return ''
          })

        this.push(contents)
        next()
      })
    }

    browserify('./src/index.js')
      .transform(extract, {
        file: './public/styles.css',
        regex: /<style>([\s\S]+?)<\/style>/g,
        capture: 1
      })
      .bundle().on('error', onError)

**Comment by goto-bus-stop** [comment]
you can use an event listener to do this:

```js
var file = './public/styles.css'
var b = browserify('./src/index.js')
  .on('bundle', function () { fs.unlinkSync(file) })
  .transform(extract, { file: file, ... })
  .bundle()
  .on('error', onError)
```

or you can write a small plugin wrapper around the transform that does the same:

```js
module.exports = function extractPlugin (b, opts) {
  b.on('bundle', function () { fs.unlinkSync(opts.file) })
  b.transform(extract, opts)
}
// used as
b.plugin('./extractPlugin', { file: './public/styles.css', ... })
```

**Comment by RedHatter** [comment]
Thank you. That works perfectly.

If anyone is interested here's the final plugin.

    const through = require('through2')
    const fs = require('fs')

    function appendReplacer (file, capture, ...match) {
      fs.appendFile(file, match[capture || 0],
        err => { if (err) throw err })

      return ''
    }

    function extract (file, options) {
      let replacer = appendReplacer.bind(this, options.file, options.capture)
      return through(function (buf, enc, next) {
        let contents = buf.toString('utf8').replace(options.regex, replacer)
        this.push(contents)
        next()
      })
    }

    module.exports = function extractPlugin (b, options) {
      b.on('bundle', function () {
        try { fs.unlinkSync(options.file) }
        catch (e) {
          if (e.code != 'ENOENT') throw e
        }
      })
      b.transform(extract, options)
    }
