### ISSUE TITLE
Parsing a json very strict about exension

### ISSUE THREAD

**Issue by briantjacobs** [browserify/browserify#1790]
A feature of browserify is that is allows .json to be imported and automatically prepended with `module.exports` (https://github.com/browserify/browserify/blob/master/index.js#L620). 

Its regex to determine when to append this is pretty strict about using `.json`. For example, if I try to import a file with `.geojson` or `.topojson`, these files get parsed as `.js` which is not what I want and throw an error. I can overcome this by manually adding a  `module.exports` within those files or renaming the files with `.json`

I would like to see an option to provide other extensions to process as json. This is a different issue than the `extensions` options already within the api.

**Comment by goto-bus-stop** [comment]
browserify follows the node.js behaviour here, but you can use a transform to prepend `module.exports=`:

```js
// jsonTransform.js
var through = require('through2')
module.exports = function (file) {
  var stream = through()
  if (/\.(geo|topo)json$/.test(file)) stream.push('module.exports = ')
  return stream
}
```

```
browserify -t ./jsonTransform
```

**Comment by briantjacobs** [comment]
Thanks for this. Found more details and some other workarounds here: https://github.com/nodejs/node-v0.x-archive/issues/6073

**Comment by goto-bus-stop** [comment]
are those options workable for you? / can we close this?

**Comment by briantjacobs** [comment]
Yes please close. Thanks
