### ISSUE TITLE
Is it possible to export a global instead of having UMD?

### ISSUE THREAD

**Issue by btilford** [browserify/browserify#1791]
My scenario is that I have a library that will be included in other (web) projects, for those AMD/UMD is totally fine. However, I'm also using the same code in another project by injecting it (a local file) to a headless chrome (using puppeteer) which causes issues since it will detect AMD from the page it's injected on then define a bunch of anonymous modules and then I'm unable to access the library modules from the puppeteer script. 

I've looked at `deumdify` and `browserify-derequire` but wasn't able to get them to work using `grunt-browserify` due to errors.

Really trying to avoid having to manage a concat configuration.

**Comment by goto-bus-stop** [comment]
deumdify seems like a perfect fit--what errors are you getting?

**Comment by goto-bus-stop** [comment]
you can also manually export a global by creating a separate bundle with a different entry point:

```js
// entryGlobal.js
window.MyLib = require('./entry')
```

**Comment by btilford** [comment]
I don't think manually exporting will work since it gets wrapped in UMD **and** the site uses AMD. Basically the UMD detects requirejs being present and nothing in the `factory` will run until that module is required. 

`deumdify` did seem like the answer but I'm not sure if running it through the `grunt-browserify` plugin causes issues or it has a bug. Basically when `deumdify(browserify)` is called it gets passed the path to the entry point. Which causes the error 
```
Fatal error: Cannot read property 'standalone' of undefined
TypeError: Cannot read property 'standalone' of undefined
  at deumdify (/project/node_modules/deumdify/index.js:97:28)
  at nr (/project/node_modules/module-deps/index.js:301:23)
  at onfile (/project/node_modules/resolve/lib/async.js:56:21)
  at onex (/project/node_modules/resolve/lib/async.js:104:32)
  at /project/node_modules/resolve/lib/async.js:24:24
  at FSReqWrap.oncomplete (fs.js:167:5)


```
![deumdify](https://user-images.githubusercontent.com/248725/34576481-417acf0e-f13b-11e7-93a6-c510bc5087d5.jpg)

**Comment by goto-bus-stop** [comment]
oh yeah you're right--the separate entry point only works when the `standalone` option is not specified (or false). i guess grunt-browserify builds UMD by default? i'm not sure if it has an option to disable that.

when using deumdify make sure to pass it as a plugin (`plugin: ['deumdify']`). since the `browserify` variable is a string in your debugger screenshot i'm guessing you may have been passing it as a transform instead.

**Comment by btilford** [comment]
Yeah, the grunt plugin seems to be lacking some configuration options or at least documentation on how to use them. Using it as a plugin causes the same error when checking `browserify._options.standalone` but I do have the `browserify` object instead of the path. Same error since `browserify._options` is undefined though.

Config (or at least one of the last versions I've tried)
```
var gruntBrowserify = {
    options: {
        debug: true,
        standalone: 'option.test', // where does the standalone or debug option go for the grunt plugin???
        browserifyOptions: {
            standalone: 'option.browserify.test',
            debug: true
        },
        transform: [
            'decomponentify',
            [
                "babelify",
                {
                    presets: [
                        [
                            'env',
                            {
                                targets: {
                                    browsers: [
                                        'last 2 versions',
                                        'ie >= 10'
                                    ]
                                }
                            }
                        ]
                    ],
                    plugins: [
                        'deumdify'
                    ]
                }
            ]


        ]
    },
    files: {
        'dist/vanilla.js': ['index.js']
    }
}
```

**Comment by goto-bus-stop** [comment]
It looks like you're passing deumdify as a plugin to the babelify transform—it should be passed as a plugin to browserify itself. I don't know exactly where to pass options with grunt-browserify, it might be best to ask over there instead

**Comment by goto-bus-stop** [comment]
anyway, i think we'll move this to #1073 :)
