### ISSUE TITLE
Browserify packaging Vue project, route using HTML5 History API, manually refreshing page blanks

### ISSUE THREAD

**Issue by antiantian** [browserify/browserify#1800]
Browserify packaging Vue project, routing using HTML5 History API, manually refreshing page blank, hash routing is not a problem
![qq 20180117151310](https://user-images.githubusercontent.com/23133017/35030400-c8562f60-fb99-11e7-9366-bfa4d497805b.png)

![qq 20180117151240](https://user-images.githubusercontent.com/23133017/35030410-d714852e-fb99-11e7-8801-18a08d8524b7.png)

Project web site: https://github.com/antiantian/browser-sync-Single-Page-Applications

**Comment by goto-bus-stop** [comment]
It can't find your bundled JS file when the path has changed. Eg if you're doing `<script src="bundle.js"></script>`, it will look for different files depending on the page you are on:

 - `/` → `/bundle.js`
 - `/firestart/newDetails` → `/firestart/bundle.js`

Instead use an absolute path for your script tag: `<script src="/bundle.js"></script>`
