### ISSUE TITLE
Is object spread not supported yet?

### ISSUE THREAD

**Issue by lunaroyster** [browserify/browserify#1802]
```
  let rules = {...RULES, ...overriddenRules}
               ^
ParseError: Unexpected token
```

Array destructuring works alright, but Browserify doesn't seem to like object destructuring. IIRC, both were implemented in the same ES revision, so it's somewhat weird that object destructuring fails while array destructuring, async/await, let/const all work.

**Comment by goto-bus-stop** [comment]
Object spread syntax is not yet in any standard. It [should work](https://github.com/browserify/browserify/blob/master/test/spread/main.js) in browserify 15.2, though. Are you using any transforms?

**Comment by goto-bus-stop** [comment]
Oh; it looks like it may not yet work if you run browserify on a Node version < 8, PRing a fix in https://github.com/substack/node-syntax-error/pull/20

**Comment by ljharb** [comment]
Object spread syntax is officially in EcmaScript as of a week ago, fwiw.

**Comment by goto-bus-stop** [comment]
Should be fixed as of https://github.com/browserify/syntax-error v1.4.0; run `npm update` to get it. thanks!
