### ISSUE TITLE
Browserify https://www.npmjs.com/package/smb2 doesn't work

### ISSUE THREAD

**Issue by Jomme5** [browserify/browserify#1806]
I tried to browerify this npm-package for use in a phonegap/cordova app. But got an 'not defined' error when I try to use the main object('SMB2'). How can you browserify this package?

**Comment by goto-bus-stop** [comment]
smb2 uses the Node `net` module which is not possible to support in browserify. I've never used cordova, so I don't know if it includes a `net` module or anything that could be used instead.
