### ISSUE TITLE
TypeError: spawn is not a function

### ISSUE THREAD

**Issue by krzischp** [browserify/browserify#1816]
I've installed browserify, I want to run a shell command line in my js file on the client side.
Here is my html script:

  [<!DOCTYPE html>
  <html>
  <head>
  <meta charset="utf-8">
  <title>Animate a page</title>
  </head>
  <body>
  <form>
      <p>Texte à l'intérieur du formulaire</p>
  </form>
  <script src="bundle.js">  
  </script>
  </body>
  </html>

and my js script:

  alert('Hello World!');
 	var spawn = require('child_process').spawn;
	const ls = spawn('ls', ['-lh', '/usr']);

	ls.stdout.on('data', (data) => {
  	console.log(`stdout: ${data}`);
	});

	ls.stderr.on('data', (data) => {
  	console.log(`stderr: ${data}`);
	});

	ls.on('close', (code) => {
  	console.log(`child process exited with code ${code}`);
	});

And I ran:
browserify piscari_main.js > bundle.js

The bundle.js file is the following one:

(function(){function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s}return e})()({1:[function(require,module,exports){
 alert('Hello World!');
 	var spawn = require('child_process').spawn;
	const ls = spawn('ls', ['-lh', '/usr']);

	ls.stdout.on('data', (data) => {
  	console.log(`stdout: ${data}`);
	});

	ls.stderr.on('data', (data) => {
  	console.log(`stderr: ${data}`);
	});

	ls.on('close', (code) => {
  	console.log(`child process exited with code ${code}`);
	});
},{"child_process":2}],2:[function(require,module,exports){

},{}]},{},[1]);

I also ran: 
npm install child_process
When I build my project, and click on the button to display the html page, I get the following error in the browser terminal:

TypeError: spawn is not a function

How can it be?
Thanks in advance for your help!

**Comment by goto-bus-stop** [comment]
You can't spawn processes in the browser, so browserify does not implement the child_process module. If you want to spawn a process, you would have to do it on a server, and your browser bundle could ask the server to do it. See #1780 and #1795 for some suggestions.
