### ISSUE TITLE
Error: Cannot find module

### ISSUE THREAD

**Issue by abidrana7** [browserify/browserify#1825]
while trying to execute the command `browserify properties.spec.js -o bundle.js` got the following erroe:

Error: Cannot find module './C:/Users/Abid/AppData/Roaming/npm/node_modules/browserify/node_modules/is-buffer/index.js' from 'D:\protractorSol\gitLabRepos\myzameenprotractorsol\node_modules\http-signature\lib'

**Comment by goto-bus-stop** [comment]
Thanks for the report; this is caused by https://github.com/browserify/insert-module-globals/issues/74

**Comment by abidrana7** [comment]
@goto-bus-stop 

sorry, i'm unable to get you at this point. Can you please elaborate more on this?

**Comment by goto-bus-stop** [comment]
The error happens because of a bug in `insert-module-globals`. I made a fix here: https://github.com/browserify/insert-module-globals/pull/75

**Comment by goto-bus-stop** [comment]
Fixed in insert-module-globals :package: 7.0.6, do `npm update` to get it. Thanks!
