### ISSUE TITLE
Browserify depends on unlicensed code

### ISSUE THREAD

**Issue by kylef** [browserify/browserify#1828]
The browserify package depends on various other packages which do not have valid licenses. This makes it hard to install browserify as in doing so you'd be making possibly illegal copies of the dependencies. Some declare that they follow the MIT license in package.json, but as they do not include a copyright notice in the NPM package it would be against the license to make a copy (such as running `npm install -g browserify`).

I think in most of the cases, the linked issues and pull requests can be resolved to create new releases of the dependencies so I've filled this bug to track in browserify. However in the case of jsonify it seems that it may not be so clear and perhaps the best course of action would be to find an alternative solution.

I've listed all of the dependencies that I spotted which do not have a valid license and opened issues or PRs on the respective packages:

- [x] jsonify@0.0.0 (Public Domain) - missing full license text
    - See discussion at https://github.com/substack/jsonify/pull/7
- [x] browserify-cipher@1.0.0 (MIT) - missing full license text
    - License added to repo in https://github.com/crypto-browserify/browserify-cipher/issues/2 but the NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] browserify-des@1.0.0 (MIT) - missing full license text
    - License added to repo in https://github.com/crypto-browserify/browserify-des/issues/2 but the NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] buffer-from@1.0.0 (MIT) - missing copyright notice, missing full license text
    - Open pull request to solve this, let's hope the author accepts having a license file and performs a release https://github.com/LinusU/buffer-from/pull/4
- [x] create-ecdh@4.0.0 (MIT) - missing full license text
    - License added to repo in https://github.com/crypto-browserify/createECDH/issues/10 but the NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] create-hash@1.1.3 (MIT) - missing copyright notice, missing full license text
    - License added to repo in but the NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] create-hmac@1.1.6 (MIT) - missing copyright notice, missing full license text
    - License added to repo in but the NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] diffie-hellman@5.0.2 (MIT) - missing full license text
   - Created a PR to add a license file https://github.com/crypto-browserify/diffie-hellman/pull/29
   - The current NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] indexof@0.0.1 (UNKNOWN) - missing copyright notice
    - Published NPM package does not contain a license
    - Master does, filed issue to make a release https://github.com/component/indexof/issues/6
- [x] minimalistic-assert@1.0.0 (ISC) - missing copyright notice, missing full license text
    - Published NPM package does not contain a license
    - Master does, issue tracking release: https://github.com/calvinmetcalf/minimalistic-assert/issues/4
- [x] parse-asn1@5.1.0 (ISC) - missing copyright notice, missing full license text
    - License added to repo in https://github.com/crypto-browserify/parse-asn1/pull/27 but the NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] path-parse@1.0.5 (MIT) - missing full license text
    - Published NPM package does not contain a license
    - There is open PR to add license https://github.com/jbgutierrez/path-parse/pull/2
- [x] public-encrypt@4.0.0 (MIT) - missing copyright notice, missing full license text
    - Open PR to add license https://github.com/crypto-browserify/publicEncrypt/pull/14
   - The current NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice.
- [x] component-indexof@0.0.3 (UNKNOWN) - missing license type, copyright notice
    - Open Issue at https://github.com/component/indexof/issues/6
   - The current NPM package does not yet contain a license file and therefore NPM release is not compliant with the license as it is a copy which does not contain the copyright notice. The repository does indeed contain the license but is unreleased.

**Comment by ljharb** [comment]
If `path-parse` is only included via `resolve`, that'll likely be removed in v2 of resolve in favor of a different dependency.

**Comment by dcousens** [comment]
@calvinmetcalf licenses! :smiley:

**Comment by goto-bus-stop** [comment]
indexof is replaced by component-indexof, which includes a license, in vm-browserify@1, so we only need to bump that dependency

**Comment by calvinmetcalf** [comment]
ok all of the cryptobrowserify ones are done except create-hash which I think has a breaking change snuck into master so I almost certaily don't want to publish that one as is

**Comment by calvinmetcalf** [comment]
pull for create hash is up crypto-browserify/createHash#22

**Comment by calvinmetcalf** [comment]
ok done on my end (as far as I know)

**Comment by goto-bus-stop** [comment]
published browserify@16.2 which removes the indexof dep.

**Comment by kylef** [comment]
Thanks for the work here all, I really appreciate it! Especially to @calvinmetcalf for releasing various libraries with LICENSE so quickly.

> published browserify@16.2 which removes the indexof dep.

There seems to be two indexof NPM packages, `indexof` and `component-indexof` which are both published from same source https://github.com/component/indexof/ according to the package.json of the NPM packages. browserify@16.2 removes `indexof` but also introduces it back via `component-indexof` so this one is still problematic.

**Comment by goto-bus-stop** [comment]
huh, i coulda sworn component-indexof had a license added. you're right, it does not :see_no_evil:

**Comment by goto-bus-stop** [comment]
just added a hand written polyfill for indexOf to vm-browserify@1.0.1. Probably makes sense to just remove those, most other browserify builtins haven't supported IE8 for a while.

**Comment by Jukilum** [comment]
It looks like buffer-from has had a license added.

**Comment by goto-bus-stop** [comment]
path-parse@1.0.6 includes a license file.
