### ISSUE TITLE
Some of packages use the same version in package.json

### ISSUE THREAD

**Issue by Alexhha** [browserify/browserify#1831]
Hello,

during publishing packages to a scope faced with the following error

```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! forbidden cannot modify pre-existing version: 11.0.1.: @SCOPE1/browserify
```
At least the following packages 

https://github.com/browserify/browserify/archive/11.0.1.tar.gz
https://github.com/browserify/browserify/archive/11.1.0.tar.gz
https://github.com/browserify/browserify/archive/5.11.1.tar.gz
https://github.com/browserify/browserify/archive/5.11.2.tar.gz

use the same version in package.json

**Comment by ljharb** [comment]
That’s not something that’s possible to fix, without overwriting git tags.

It was probably mistakenly pushed up to Github with the wrong version and manually edited locally before running npm publish; i don’t think there’s anything to be done here (nor do i understand why you’d publish old versions of browserify to a scope)

**Comment by Alexhha** [comment]
> nor do i understand why you’d publish old versions of browserify to a scope

we are testing npm repository in Artifactory, and for our tests I have to use a scope.

I just wanted to inform you about this small issue. If you can't do anything - you probably feel free to close the issue.
