### ISSUE TITLE
TypeError: require.resolve is not a function

### ISSUE THREAD

**Issue by rivetweb** [browserify/browserify#1832]
trying to use uglifyjs
after compile 

browserify app.js -o app.min.js

and run page in browser

have this error

```

var uglifyjs = require('uglify-js');
var code = 'some_code();';
var result = uglifyjs.minify(code);
```

**Comment by goto-bus-stop** [comment]
uglify-js can't be easily browserified unfortunately. it dynamically generates modules by reading from the filesystem and concatenating them at runtime which doesn't work in the browser.

**Comment by goto-bus-stop** [comment]
You can use the UglifyJS CLI to generate a node module though:

```bash
uglifyjs --self --wrap exports > uglify.js
```

And then use that instead:

```js
var minify = require('./uglify').minify
```
