### ISSUE TITLE
"got" library needs "setImmediate" package when using Browserify

### ISSUE THREAD

**Issue by unquietwiki** [browserify/browserify#1833]
https://github.com/sindresorhus/got/issues/486

They thought it was you all's issue, regarding polyfill creation.

- https://github.com/sindresorhus/got/
- https://github.com/yuzujs/setImmediate/

**Comment by goto-bus-stop** [comment]
We should probably merge this: https://github.com/browserify/insert-module-globals/pull/40

**Comment by ljharb** [comment]
Since that's now merged, should this be closed? (if not now, then when it's released?)

**Comment by goto-bus-stop** [comment]
:package: insert-module-globals 7.1.0
