### ISSUE TITLE
Common lodash practice with standalone build causes standalone build failure

### ISSUE THREAD

**Issue by niftylettuce** [browserify/browserify#1847]
If you have the following code in your file that is to be bundled (e.g. via `browserify src/index.js -o dist/my-project.js -s MyProject -d -t babelify`), then it will give the error below when `require`'d (e.g. via `"browser"` field in `package.json`) in another project that is bundling similarly with browserify:

```js
// <https://lacke.mn/reduce-your-bundle-js-file-size/>
// <https://github.com/lodash/babel-plugin-lodash/issues/221>
const isError = require('lodash/isError');
const isArray = require('lodash/isArray');
const isEmpty = require('lodash/isEmpty');
const pick = require('lodash/pick');
const isFunction = require('lodash/isFunction');
```

```sh
> browserify src/index.js -o dist/my-other-project.js -s MyOtherProject -d -t babelify

Error: Cannot find module './_getNative' from '/Users/user/Projects/my-other-project/node_modules/my-project/dist'
    at /Users/user/Projects/my-other-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/Users/user/Projects/my-other-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/user/Projects/my-other-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/user/Projects/my-other-project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:152:21)
```

Possibly related to these issues:
* https://github.com/browserify/browserify/issues/1068
* https://github.com/goto-bus-stop/browser-pack-flat/issues/25
* https://github.com/browserify/browserify/issues/932

**Comment by goto-bus-stop** [comment]
the `browser` field really should not contain a browserified bundle. it should contain source files that can be bundled by a user that depends on the package.

see https://github.com/browserify/browserify/issues/1773#issuecomment-341961421, you can use derequire to create a bundle that can be `require()`d if you really must.
