### ISSUE TITLE
Obscure error reporting?

### ISSUE THREAD

**Issue by loldrup** [browserify/browserify#1848]
I'm using Browserify to bundle my frontend code. As my IDE (IntelliJ) started whining about my use of 'var', I decided to go trough my code, replacing them with `const` (and, if that fails, then with `let`).
However, after having fixed some bugs, repored by Browserify, I received a less clearly described error, which leaves me little breadcrumb to figure out what is wrong.

This is the console output:

```
> auchitect-frontend@0.1.0 test C:\Users\Jon\Aukitekt\frontend
> node build_test.js


events.js:154
      throw er; // Unhandled 'error' event
      ^
SyntaxError: Unexpected token
npm ERR! Test failed.  See above for more details.

Process finished with exit code 1
```

This is the content of my `build_test.js` script:

```
var browserify = require('browserify');
//var browserifyInc = require('browserify-incremental');
var unflowify = require('unflowify');
var fs = require('fs');

var options = {
    basedir: './js/',
	debug: false,
    noParse: ['three', 'qunitjs']
	// cache: {},                     // option required by browserrifyInc
	// packageCache: {},              // option required by browserrifyInc
	// fullPaths: true,               // option required by browserrifyInc
	// cacheFile: './buildCache.json' // option required by browserrifyInc
};

var outputFileStream = fs.createWriteStream('./js/tb.js');

var b = browserify('./test.js', options);

b.transform(unflowify);

// browserifyInc( b );

// b.on('time', function (time) { process.stdout.write('build time: ' + time) } )

b.transform(unflowify).bundle().pipe(outputFileStream);  // process.stdout
```

**Comment by ljharb** [comment]
You should be linting your code prior to run any other tools on it; that will reveal the syntax error.

**Comment by goto-bus-stop** [comment]
browserify should also attempt to show the syntax error location, this is what i get:

```
➜ npm install browserify unflowify
+ unflowify@1.0.1
+ browserify@16.2.2

➜ cat t.js
const a
null

➜ node
> require('browserify')('t.js').transform('unflowify').bundle(); ''
''
> Thrown:
/tmp/t.js:2
null
^
ParseError: Unexpected token
```

which browserify and node versions are you using?
a runnable example in a gist or github repository that reproduces the problem would be super helpful.

**Comment by loldrup** [comment]
I did `git reset --hard` so I no longer have the bug. I'll be fixing the var statements as I go along.
And also installing ESlint :)
