### ISSUE TITLE
Piping into browserify doesn't work

### ISSUE THREAD

**Issue by ericmorand** [browserify/browserify#1868]
I have a read stream that pipe to stdout:

```
const {Readable} = require('stream');

let data = `console.warn('FOO');`;

const stream = new Readable();

stream.push(data);
stream.push(null);
stream.pipe(process.stdout);
```

Its name is entry.js. When executing node entry.js, I can confirm that `console.warn('FOO');` is successfully piped to stdout.

But when I try to pipe it into browserify, the resulting bundle doesn't contain `console.warn('FOO');`:

`node entry.js | browserify`

How can I pipe into browserify using the CLI?

**Comment by goto-bus-stop** [comment]
Use `browserify -`:

```bash
node entry.js | browserify
```

**Comment by ericmorand** [comment]
Thank you so much. Is it a standard way of piping that I don't know about or something specific to Browserify?

**Comment by goto-bus-stop** [comment]
It's conventional in many Unixy command line tools

**Comment by ericmorand** [comment]
Good to know. Thanks for your help.
