### ISSUE TITLE
Error: cannot find module 'user\node_modules\puppeteer\utils\browser\WebSocket'

### ISSUE THREAD

**Issue by koffe1n** [browserify/browserify#1883]
I bundle a project using **browserify**, previously installed puppeteer with npm install -g puppeteer.
There is a part of my code: const puppeteer = require('puppeteer'); 
When im trying to browserify my js file like this: browserify js/main.js -o js/findem.js -d
im getting Error: cannot find module 'user\node_modules\puppeteer\utils\browser\WebSocket' from 'user\node_modules\puppeteer\lib'
How can i solve this issue?

**Comment by ljharb** [comment]
Is puppeteer even something that could ever work in a browser?
