### ISSUE TITLE
"SyntaxError: Unexpected token"

### ISSUE THREAD

**Issue by tjconcept** [browserify/browserify#1884]
I'm seeing the `SyntaxError: Unexpected token` when using the syntax `{...o}`, but only occasionally.

It only occurs when a file gets to a certain size, but does not seem to be bound by size alone.

I have not yet been able to produce a reproducible test.

**Comment by nsinghal90** [comment]
The SyntaxError: Unexpected token is coming up on trying to browserify my project files. I am running browserify in a gulp task in a CI job. One of the error is:
<pre><code>14:04:03 [14:04:03] Browserify error: /Users/jenkins/.jenkins/workspace/x/x/x/x/x.js: Unexpected token, expected "${" (19:10)
14:04:03
14:04:03   17 |
14:04:03   18 | function generate(env) {
14:04:03 > 19 |   return `${env}`;
14:04:03      |           ^
14:04:03   20 | }
14:04:03   21 | 
</code></pre>
I am on `browserify: "^16.0.0"` and gulp v4. I have even seen browserify segfault multiple times.

**Comment by goto-bus-stop** [comment]
That looks like babelify is throwing the error, browserify errors don't look that nice :sweat_smile: It's surprising though, since babel and browserify both support that syntax by default.

**Comment by goto-bus-stop** [comment]
@tjconcept Regarding the original post, are you using any plugins or transforms? it may be an issue with a transform not waiting for its input stream to complete. When that happens it may try to parse an incomplete source file.

**Comment by tjconcept** [comment]
@goto-bus-stop indeed removing the `brfs` transform made it go away, and updating `brfs` seemed to fix it.

Completely unrelated: why did `acorn` become a peer dependency? They are so annoying..

**Comment by goto-bus-stop** [comment]
The acorn-related dep tree in browserify looks a bit like:

```bash
acorn-node # acorn wrapper with default config for new syntax features supported by node
 - acorn-dynamic-import # has a peer dep on acorn
 - acorn
```

so we depend on acorn and you don't need to manually install it, but sometimes npm warns anyway, i think when you have multiple acorn versions. i haven't really looked into what would be required fix the warning because it doesn't appear to actually break anything, and it's safe to ignore.

**Comment by tjconcept** [comment]
Interesting.

If I don't install `acorn` manually though, I'm seeing this:

```
Error: Cannot find module 'acorn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> ([...]/node_modules/acorn-dynamic-import/lib/index.js:18:14)
```

**Comment by tjconcept** [comment]
Trashing everything npm-ish and reinstalling packages solved the above, so I guess it was some other mishap. Thanks again.

**Comment by tjconcept** [comment]
A note to future me: `envify` is causing the same issue due to an outdated "esprima" dependency. https://github.com/browserify/tinyify has a patched version.
