### ISSUE TITLE
Cannot find module 'uws' - trying to pack HTTP Express server

### ISSUE THREAD

**Issue by ZeroByter** [browserify/browserify#1898]
I have a standard Express/Socket.io server, and I am trying to turn it into an executable 'exe' using PKG and using Browserify to pack the scripts in order to get PKG to work.

In my server, I am requiring Express as `var app = require('express')();`

When trying to pack the scripts, I get the error `Error: Cannot find module 'uws' from 'E:\Documents\Projects\Website Projects\nodejs\unfucking skillz plugin\node_modules\engine.io\lib'`

Any way to fix this?

**Comment by goto-bus-stop** [comment]
`uws` is probably an optional dependency. you can use `-x` to exclude a module:

```
browserify -x uws app.js
```

(my understanding is that pkg should handle bundling already, though?)

**Comment by ZeroByter** [comment]
PKG is supposed to, but browserify does it better it seems.

Thanks for your suggestion, it worked :)
