### ISSUE TITLE
Browserifying, unable to use --require to override 'fs'

### ISSUE THREAD

**Issue by elijah1210** [browserify/browserify#1904]
Hi,

I am attempting to browserify chai-jest-snapshot to work with requirejs. 
`browserify -r fs:memfs -s 'lib/chai-jest-snapshot' node_modules/chai-jest-snapshot/dist/index.js -o tests/lib/chai-jest-snapshot.js`

When I require it via requirejs, I receive an empty object.

If I remove the -r fs:memfs, then it works as expected except fs calls fail due to the lack of functions on default.

**EDIT:**
I have also attempted the following which works well for browserifying chai-jest-snapshot but not overriding fs.
`browserify -r chai-jest-snapshot -s 'lib/chai-jest-snapshot' > tests/lib/chai-jest-snapshot.js`

**Comment by goto-bus-stop** [comment]
it should be the other way around: `-r realmodule:aliasname`

`browserify -r memfs:fs` should do the trick
