### ISSUE TITLE
fail in sqlite3

### ISSUE THREAD

**Issue by virginiadb** [browserify/browserify#1909]
when "browserify -r sqlite3 --node -s CMD -o agent/sqlite3.js"
find " package.json does not exist at XXXXXXX"
Sheldon Lee Cooper:Danger!Danger!Danger!
Me:help!help!help!
I am crying.

**Comment by goto-bus-stop** [comment]
sqlite is (partially) a native C++ module, so it does not work in the browser. To use a database in the browser, check out the web API [indexedDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) or a userland database like [levelDB](https://www.npmjs.com/package/level).

**Comment by virginiadb** [comment]
Thank you for helping.But I am working on get web history of Chrome and Firefox.They use sqlite3 so I have to use it.

**Comment by goto-bus-stop** [comment]
It is impossible to get browser history or read those files from inside a browser. If you are reading the files in a separate application, you don't need browserify.

On May 13, 2019 8:23:39 AM GMT+02:00, daibing <notifications@github.com> wrote:
>Thank you for helping.But I am working on get web history of Chrome and
>Firefox.They use sqlite3 so I have to use it.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/browserify/browserify/issues/1909#issuecomment-491691234

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by virginiadb** [comment]
My application is something special.It is a server-forensic application,so it is like a front-end application as well as a back-end application.But I have got a solution yet.Thank you for helping and can I have your e-mail,please?
