### ISSUE TITLE
browseify looking for babel-core

### ISSUE THREAD

**Issue by Zaptronic** [browserify/browserify#1911]
I'm using babel 7 and the naming changed to @babel/core but when I run the   command I get an error: Cannot find module 'babel-core' which it cannot find anymore. Is this a bug or am I doing something wrong?

**Comment by goto-bus-stop** [comment]
Please share your configuration and the command you're running. browserify doesn't do anything with babel so it's almost certainly a configuration problem.

**Comment by Zaptronic** [comment]
These are my dev dependencies:
        "@babel/cli": "^7.4.4",
        "@babel/core": "^7.4.5",
        "@babel/plugin-transform-property-mutators": "^7.2.0",
        "@babel/plugin-transform-template-literals": "^7.4.4",
        "@babel/preset-env": "^7.4.5",
        "babel-core": "^6.26.3",
        "babel-plugin-check-es2015-constants": "^6.22.0",
        "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
        "babel-plugin-transform-es2015-block-scoped-functions": "^6.22.0",
        "babel-plugin-transform-es2015-block-scoping": "^6.26.0",
        "babel-plugin-transform-es2015-computed-properties": "^6.24.1",
        "babel-plugin-transform-es2015-for-of": "^6.23.0",
        "babel-plugin-transform-es2015-function-name": "^6.24.1",
        "babelify": "^10.0.0",
        "node-sass": "^4.12.0",
        "watch": "^1.0.2",
        "watchify": "^3.11.1"

And these are my npm scripts:

"browserify": "browserify public/js/sketch.js -o public/js/dist/bundle.js",
"watchify": "watchify public/js/sketch.js -o public/js/dist/bundle.js",
"sass": "node-sass -w public/scss/ -o public/css/",
"babel": "babel public/js/dist -d public",
"build": "npm i && npm audit fix && npm run browserify && npm run babel",

**Comment by goto-bus-stop** [comment]
What about browserify transforms and babelrc configuration? Is this happening when you run `npm run browserify`?

**Comment by Zaptronic** [comment]
This is my .babelrc file
{
    "presets": [
        "@babel/preset-env"
    ],
    "compact": true,
    "plugins": [
        "transform-es2015-arrow-functions",
        "check-es2015-constants",
        "transform-es2015-block-scoping",
        "transform-es2015-block-scoped-functions",
        "transform-es2015-function-name",
        "@babel/plugin-transform-template-literals",
        "@babel/plugin-transform-property-mutators",
        "transform-es2015-computed-properties",
        [
            "transform-es2015-for-of",
            {
                "loose": true
            }
        ]
    ]
}

**Comment by goto-bus-stop** [comment]
Thanks. The problem is that you're trying to use Babel 6 plugins with Babel 7. These plugins internally do `require('babel-core')` for various things. When you upgrade to Babel 7, you also have to upgrade to the Babel 7 compatible versions for _every_ plugin you use.

In your case, you can actually get rid of all the Babel 6 plugins, because the ones you use are all included in @babel/preset-env:

```json

{
  "presets": [
    "@babel/preset-env"
  ],
  "compact": true,
  "plugins": [
    "@babel/plugin-transform-property-mutators",
  ]
}
```

**Comment by Zaptronic** [comment]
That seems to work. Thanks. It was a configuration error on my part.
