### ISSUE TITLE
Print pathinfo for each file

### ISSUE THREAD

**Issue by kraftwer1** [browserify/browserify#1914]
In Webpack, there's an option `output.pathinfo` to include comments in bundles with information about the contained modules, e.g.:

    (window["webpackJsonp"] = window["webpackJsonp"] || []).push([["vendor"],{
    /***/ "./node_modules/@uirouter/angularjs/release/ui-router-angularjs.js":
    /*!*************************************************************************!*\
      !*** ./node_modules/@uirouter/angularjs/release/ui-router-angularjs.js ***!
      \*************************************************************************/
    /*! no static exports found */
    /***/ (function(module, exports, __webpack_require__) {
    (function (global, factory) {
        undefined;

Is there something similar for Browserify?

**Comment by goto-bus-stop** [comment]
This can be implemented with a global transform. I'm not aware of any existing transforms for this, but creating one is fairly simple:

```js
// add-path-transform.js
var { PassThrough } = require('stream')
var path = require('path')

module.exports = function (file, opts) {
  var basedir = opts._flags && opts._flags.basedir ? opts._flags.basedir : process.cwd()
  var s = PassThrough()
  s.write('/** file: ' + path.relative(basedir, file) + ' */\n')

  return s
}
```

```bash
browserify app.js -g ./add-path-transform
```
