### ISSUE TITLE
how to export a class?

### ISSUE THREAD

**Issue by wuzhenda** [browserify/browserify#1915]
I have a class like functions and it has some prototype funciton,but after export modules,can't get the prototype funciton directly.

```jsx
function ModbusRTU() {
    var self = this;			
	// formation function
	this.formRequestBuffer=function (slave, fc, register, value){		
	};
};	

////// Necesarry Functions
ModbusRTU.prototype.getProductInfo = function(slaveAddr,address) {
    return this.formRequestBuffer(slaveAddr,3,address,32);
};

//////export module
module.exports = ModbusRTU;
```

when use the module,it don't get the function.

```jsx
var modbusModule = window.modbus;
            payload = modbusModule.getProductInfo(slaveId,addr);
```

but use
```jsx
var modbus_rtu = modbusModule.ModbusRTU;      
var prototype = modbus_rtu.prototype;
```
can find the function

**Comment by ljharb** [comment]
Thats just how javascript works. You made a constructor function, so you have to `new` it if you want access to prototype methods.

Closing as this is entirely unrelated to browserify.

**Comment by wuzhenda** [comment]
thanks.I got it.
