### ISSUE TITLE
__dirname is incorrect when browserifying to a subdirectory

### ISSUE THREAD

**Issue by manuth** [browserify/browserify#1920]
This issue might be related to  #1919 

## How to reproduce
Create a simple project:
***./test.json:***
```json
{
    "test": "test"
}
```

***./src/index.js:***
```js
const path = require("path");
console.log(require(path.join(__dirname, "..", "test.json"))["test"]);
```

Browserify it
```sh
npx browserify --node --debug ./src/index.js -o ./lib/index.js
```

## Expected behavior
The generated `__dirname` should either be `./src` or `./lib`.

## Actual behavior
***./lib/index.js:***
```js
(function (__dirname){
const path = require("path");

console.log(require(path.join(__dirname, "..", "test.json"))["test"]);
}).call(this,require("path").join(__dirname,"src"))
```

The generated `__dirname` points to `path.join(__dirname, "src")` which equals `./lib/src/index.js`.

**Comment by goto-bus-stop** [comment]
This is basically the intended behaviour. In the past, __dirname would be the actual absolute path to the file in `--node` builds. Now, it assumes __dirname is supposed to be browserify's `basedir`. So it works well if you do:
```
browserify src/app.js -o bundle.js
```
Conceptually in this configuration the `bundle.js` "contains" all the files that you bundled, relative to the basedir:
```
/
- bundle.js
- bundle.js: src/app.js           ← this could refer to ./src/someimg.png
- bundle.js: node_modules/somedep/index.js
- src/someimg.png
```

A solution for this use case could be an `outdir` option for the JS API, that would be automatically set if you do `-o somedir/bundle.js`. Then the paths could be rebased based on that. But the behaviour would differ between shell pipes using `>` and the `-o` parameter, which could be confusing.

Right now, you can still achieve this by changing the `basedir`. With the JS API you can do something like
```js
browserify('../src/app.js', { basedir: 'lib' })
```
With the CLI, you can do
```
cd lib && browserify ../src/app.js -o bundle.js
```

**Comment by manuth** [comment]
Awesome!
This did the trick

I didn't assume it'd be that easy to solve this problem.
