### ISSUE TITLE
Bundle very big after browserified

### ISSUE THREAD

**Issue by sicadev** [browserify/browserify#1921]
Hello,

im using browserify this way:
browserify src/renderers/renderer.js -o src/renderers/bundle.js

i just realised after deploying my app online and wondering why it was so slow loading that my bundle files are from initial 11Ko to 1.65Mb browserified !!

What are the best options to minify and get something lot smaller?

**Comment by goto-bus-stop** [comment]
You probably have some big dependencies. You can use https://github.com/browserify/tinyify to minify everything and remove unused code.

**Comment by christopheSeeka** [comment]
Thank you, was already trying uglifyify which reduced from 1.6Mb to 700Ko already, will try tinyify which also include uglifyify i think.

**Comment by sicadev** [comment]
Thank you, was already testing uglifyify which reduced more than 50%, will try tinyfy since it also include uglifyify too. Thanks.
