### ISSUE TITLE
browserify not recognized as an internal or external command

### ISSUE THREAD

**Issue by KQuinn1996** [browserify/browserify#1922]
I have install browserify like so

npm install -g browserify

then I try to run it:

browserify main.js > bundle.js

and Windows says

'browserify' is not recognized as an internal or external command

I've tried editing my environment variables but it still does not work, Why is this happening, no one else seems to have this problem??

**Comment by goto-bus-stop** [comment]
It's hard to say! How did you configure the PATH variable? some possibly common ideas:
- make sure to use `;` to separate the paths and not `:`
- i think you need to restart after updating the PATH variable

**Comment by KQuinn1996** [comment]
Hi, I have done what you have said and it have worked thank you very much
