### ISSUE TITLE
Is there a simple way to wrap globals?

### ISSUE THREAD

**Issue by Ayms** [browserify/browserify#1928]
Currently browserifying https://github.com/Ayms/node-Tor/blob/master/lib/node-tor.js

Per the initial design which was not intended to be modular, globals are mandatory at the nodejs level, now I was under the impression that after the browserification process everything would be wrapped or that I just had to wrap the whole code inside an anonymous function

But apparently browserify does something else, I think I know how to correct this but it is not straight forward, is there a simple way to wrap globals via browserify or a simple change to perform after?

**Comment by goto-bus-stop** [comment]
browserify wraps all your modules in anonymous functions already, but if you do `global.A = 1`, it will set a global variable. I'm not entirely clear on what you want here—should those `global.A` assignments in that file be stored on a different object instead?

**Comment by Ayms** [comment]
How does it set a global variable? (window.A=global.A ?)

I know it can look strange but the initial code was a big non modular monolithic block, so with no globals, now that it is modular I am forced to use globals (or too many changes for now) which I don't like a lot, especially inside browser

I don't know how globals work with browserify, the question is: how to make globals.A local wrapped into an anonymous function for example (a fix I think is to wrap the whole code inside another function where you redefine the globals local to this one and delete all window.A, but that's not very nice)

**Comment by Ayms** [comment]
Complement: indeed, I could use only one global for all the objects but it's a bit the same at the end, I would like to understand how browserify handles ``global``

**Comment by goto-bus-stop** [comment]
Yea, `global` becomes a reference to `window` in the browser. (caveat: in Web Workers and Service Workers, it becomes a reference to `self`, because they don't have `window`.)

If you want to avoid globals, I think one thing you could do, is create a new module `globals.js`, doing something like:
```js
exports.A = 1
```
and then refer to `require('./globals.js').A` elsewhere.

**Comment by Ayms** [comment]
The globals are not static, so this one will not work, probably your first suggestion is the best one (then I kill the global after wrapping again, unless you think there is a pb with this), thanks, closing?

**Comment by goto-bus-stop** [comment]
You can still modify them by doing:
```js
// in a.js
var globals = require('./globals.js')

globals.HELLO = 'world'

// in b.js
var globals = require('./globals.js')
console.log(globals.HELLO) // 'world'
```

**Comment by Ayms** [comment]
Not in my case in fact because the important globals are common to many modules (for example to keep the state of the Tor circuits), anyway I understand that we can not hack easily into ``global`` to make it local, so probably the best is to do what you suggested first, which in fact is very exactly what I am doing when using ``browserify a.js --s internal`` where ``internal`` becomes also a global inside browsers and is copied then deleted after

**Comment by Ayms** [comment]
Suggestion: maybe set a no-globals option so everything that goes out of browserify is in a local context (except browser's globals) and this would apply also to ``internal`` when you do ``browserify -s internal`` from ``module.exports`` where internal is a global after browserification but should not, I think

I don't know if it's easy to do
