### ISSUE TITLE
browserify with imagemine 

### ISSUE THREAD

**Issue by aa947** [browserify/browserify#1931]
### I am trying to bundle up imagemin but i get : 
**Error: Parsing file** C:\...\node_modules\fast-glob\out\readers\stream.js: 
### Unexpected token (16:10)

my main.js file:
```
const imagemin = require('imagemin');
const imageminJpegtran = require('imagemin-jpegtran');
const imageminPngquant = require('imagemin-pngquant');
(async () => {
    const files = await imagemin(['images/*.{jpg,png}'], {
        destination: 'build/images',
        plugins: [
            imageminJpegtran(),
            imageminPngquant({
                quality: [0.6, 0.8]
            })
        ]
    });
 
    console.log(files);
    //=> [{data: <Buffer 89 50 4e …>, path: 'build/images/foo.jpg'}, …]
})();
```

**Comment by goto-bus-stop** [comment]
imagemin probably isn't built to work in the browser. in your sample code, you are using `images/*.{jpg,png}`, but there is no way to read those files in the browser, because there is no filesystem.
