### ISSUE TITLE
how does one use browserify to make a pure browser file?

### ISSUE THREAD

**Issue by Pomax** [browserify/browserify#1933]
"pure" in this context being "not also set up to work with node/rjs/etc/.etc/".

Is there a way to turn a some Node.js code into "specifically for modern browsers" code without turning it into a UMD bundle when using `-s`? I'm running into issues with browserify yielding code that seems to introduce a `Browser` that doesn't actually exist, and thus yields code that can't actually be used in the browser.

STR:
1. `npm install brotli`
2. `cd node_modules/brotli`
3. `browserify index.js -o brotli.browser.js -s Brotli`
4. create an index.html with content `<!doctype html><html><head><script src="./brotli.browser.js"></script></head></html>`
5. `http-server`
6. http://localhost:8080/index.html

Result:
```
ReferenceError: Browser is not defined (brotli.browser.js:703:191)
```

If you search for `Browser` in the node_modules dir, you'll notice there are zero hits: browserify seems to have introduced it.

**Comment by goto-bus-stop** [comment]
browserify polyfills Node.js globals like `Buffer` and semi-globals like `__dirname`, but doesn't introduce any.

It looks like `Browser` is used by `brotli/build/encode.js`, which is an emscripten-compiled file. I haven't used emscripten so i don't really know what that's supposed to do.

**Comment by Pomax** [comment]
I see. guess it's time to find a better brotli library =S

Thanks!
