### ISSUE TITLE
Output script not working as expected with library in browser.

### ISSUE THREAD

**Issue by jackflyer** [browserify/browserify#1934]
Working with javascript library from [here](https://github.com/mattboldt/typed.js/blob/master/lib/typed.js). It works as expected , when used without browserify, as it creates global Typed function in browser. But when used browserify with gulp. It's not working as expected, as it not creating global function "Typed", when loaded in browser, throwing error Typed is not function.There also problems when used for other jQuery plugins.

in entry script I used
`import 'typed.js/lib/typed.js';`

**Comment by goto-bus-stop** [comment]
that library uses an UMD header, that `webpackUniversalModuleDefinition` stuff. Used without a bundler, it'll assign a global `Typed`. Used with a bundler, it will act as a module that exports a function. To use it with browserify, you need to use:
```js
var Typed = require('typed.js/lib/typed.js')
```
or if you're transpiling ES Modules
```js
import Typed from 'typed.js/lib/typed.js'
```
