### ISSUE TITLE
otps.node does not generate backend bundle

### ISSUE THREAD

**Issue by unexpectedShr3k** [browserify/browserify#1936]
related to #1452 

My intent is to generate a single bundle for the backend. This command is working:

`browserify server.js --node > _build/server.js`

but the api is not:

```
gulp.task('bundleServer', () => {
    return browserify({
            entrypoint: 'server.js',
            node: true
        })
        .bundle()
        .on('error', glog.error.bind(log, 'Browserify Error'))
        .pipe(source('server.js'))
        .pipe(gulp.dest('./build'));
});
```

This is also not working:

```
{
    entrypoint: 'server.js',
    bare: true,
    browserField: true
}
```

The error only generates this:

**build/server.js**

`(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({},{},[]);`

**Comment by goto-bus-stop** [comment]
```js
browserify({
  entrypoint: 'server.js',
  node: true
})
```

The option name for the entry point is `entries`:
```js
browserify({
  entries: 'server.js',
  node: true
})
```
It should work if you use it like that!

(Was the `entrypoint` name in documentation somewhere? If so we should update it :smile: )

**Comment by unexpectedShr3k** [comment]
damn thanks. I was mapping different tasks and merging the streams like this and I used different names for some reason and it got stuck in the back of my mind since then. tutorial influence I guess:

```
var files = [{
        dest: jsDir,
        bundleName: 'app.js',
        entrypoint: './build/public/app.js'
    }, {
        dest: jsDir,
        bundleName: 'common.js',
        entrypoint: './build/public/dependencies.js'
    }];

    var tasks = files.map(function (file) {
        browserifyOpts.entries = file.entrypoint; // <---- here
```
