### ISSUE TITLE
require a JSON file

### ISSUE THREAD

**Issue by swyveu** [browserify/browserify#1943]
this works: 
  `const data = require('./data.json')`
  `console.log(data)`
// data...

this doesn't:
  `const file = './data.json'`
  `const data = require(file)`
  `console.log(data)`   
// Error: Cannot find module './data.json'

why?

**Comment by ljharb** [comment]
Because the former is a static require (which is a best practice anyways); the latter is a dynamic require, which is not statically analyzeable, and thus no build time tool will be able to handle it.

Only pass hardcoded strings into `require`, regardless.

**Comment by swyveu** [comment]
Good to know. New to build tools, still learning. Thank you.
