### ISSUE TITLE
browserify doesn't define process variable

### ISSUE THREAD

**Issue by domino2** [browserify/browserify#1944]
Hello, 
I'm trying to browserify websql api to don't change legacy code as the websql is deprecated and the app is not working on some browsers.

For this purpose, I've downloaded the https://www.npmjs.com/package/websql
And I installed browserify latest and run
`browserify index.js --insert-globals --standalone websqlwrap > bundle.js` from the lib folder, I've include the script to the browser and got an exception saying **stream is undefined**, where the code is
```
module.exports = function (blocking) {
  [process.stdout, process.stderr].forEach(function (stream) {
    if (stream._handle && stream.isTTY && typeof stream._handle.setBlocking === 'function') {
      stream._handle.setBlocking(blocking)
    }
  })
}
```

I tried to find work around by including the 
https://github.com/defunctzombie/node-process/blob/master/browser.js
, but it's not working and there are not any implementation for the stdout and stderr anyway.

I tried also:
`browserify index.js > bundle.js`
`browserify index.js --insert-globals > bundle.js`

**Comment by goto-bus-stop** [comment]
`process` is only partially implemented. There is no such thing as standard output in the browser, so `stdout` and `stderr` do not exist.

There's a bigger problem though. The websql package builds on a different package `sqlite3`. That package uses native C++ and can not ever work in the browser. If browsers are dropping WebSQL support I don't think there is really any way to fix it without updating your app, unfortunately :( There don't seem to be any good WebSQL polyfills either.

**Comment by domino2** [comment]
ok, thank you for that
