### ISSUE TITLE
Lack of file names when bundling files transformed with Babel

### ISSUE THREAD

**Issue by djalbat** [browserify/browserify#1945]
Hi.

I am transforming files with Babel thus:

```
const babel = require(path.resolve('./node_modules/@babel/core'));

const { transform } = babel;

const source = ...,
      options = {
        'sourceMaps': inline
      };

transform(source, options, (error, result) => {
  const { code } = result;

  ...
});
```
This works fine, tranforming...
```
export const CONTACT_URI = '/contact';
```
...into...
```
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.CONTACT_URI = void 0;
var CONTACT_URI = '/contact';
exports.CONTACT_URI = CONTACT_URI;
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInVua25vd24iXSwibmFtZXMiOlsiQ09OVEFDVF9VUkkiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7QUFFTyxJQUFNQSxXQUFXLEdBQUcsVUFBcEIiLCJzb3VyY2VzQ29udGVudCI6WyIndXNlIHN0cmljdCc7XG5cbmV4cG9ydCBjb25zdCBDT05UQUNUX1VSSSA9ICcvY29udGFjdCc7XG4iXX0=
```
...for example.

I now bundle a number of these transformed files using Browserify:

```
const browserify = require(path.resolve('./node_modules/browserify'));

const options = {
  debug: true
}

const bundler = browserify(options);

bundler.add('./tmp/main.js');

bundler.bundle((error, buffer) => {
  ...
});
```
This works almost perfectly, JSX and ES6 features are shown in developer tools, for example, however the file names are missing:

![Screenshot from 2020-02-24 14-43-05](https://user-images.githubusercontent.com/17334729/75161668-17e3f800-5714-11ea-98d3-953b88f37484.png)

Have you any idea why?

Many thanks and kind regards,
James

**Comment by goto-bus-stop** [comment]
You probably need to provide something like a `sourceFilename` option to Babel so it stores the input file names in the source maps. I don't know the exact name but it should be in the `@babel/core` docs. Without that, it's impossible for browserify to know what the original file names were.

**Comment by djalbat** [comment]
This is fixed. I needed to pass the file name to Babel's `transform()` function via a `sourceFileName` property of the options. Browserify then successfully picked this up.

**Comment by goto-bus-stop** [comment]
Haha, timing :) good to hear that it's working!

**Comment by djalbat** [comment]
@goto-bus-stop Many thanks! I must credit James DiGiola on the Babel Slack channel for pointing this out to me.
