### ISSUE TITLE
Stream is undefined

### ISSUE THREAD

**Issue by AVCADO** [browserify/browserify#1953]
While bundling my JS file, I got an error in Chrome Console: `TypeError: stream is undefined add.js:19444:9`

In `add.js`, line 19444 looks like this:
```js
if (stream._handle && stream.isTTY && typeof stream._handle.setBlocking === 'function') {
      stream._handle.setBlocking(blocking)
    }
```
Any help?

**Comment by goto-bus-stop** [comment]
Could you share a stack trace?

My guess would be that you are using some module that is not intended to work in the browser.

**Comment by AVCADO** [comment]
> Could you share a stack trace?
> 
> My guess would be that you are using some module that is not intended to work in the browser.

What is a stack trace?

Module I'm trying to use is `sqlite3`.

**Comment by goto-bus-stop** [comment]
The stack trace is the stuff like this when you see an error in the console:
![image](https://user-images.githubusercontent.com/1006268/76631832-975e2d80-6542-11ea-8ec1-c85eaac987f3.png)

sqlite3 uses native Node.js addons and cannot work in the browser, unfortunately.

**Comment by AVCADO** [comment]
Ok, that makes sense.
