### ISSUE TITLE
Cut new release for latest commit

### ISSUE THREAD

**Issue by jennifer-shehane** [browserify/browserify#1956]
Can you cut a new release for this commit made 5 days ago https://github.com/browserify/browserify/commit/00c913fa345dbb7f612bdad6b4acc91c706e98b2 - where the deprecated mkdirp dependency has been removed? 

I have a lot of people using our library who do not like seeing warnings in their terminal 😞 https://github.com/cypress-io/cypress/issues/6730#issuecomment-605606441

**Comment by goto-bus-stop** [comment]
:package: 16.5.1
Thanks!
