### ISSUE TITLE
problem browserifying files with ñ á é í ó ú 

### ISSUE THREAD

**Issue by mrbianchi** [browserify/browserify#1961]
reproduce: browserify [bip39](https://github.com/bitcoinjs/bip39) and try use `bip39.validateMnemonic("famoso reino chacal rotar afectar arruga orador neón caña fogata persona piojo",bip39.wordlists.spanish) `

I have to edit manually the file changing the array with the invalid chars with one with correct chars

Also, I don't know why but visual studio code paste wrong this chars

**Comment by goto-bus-stop** [comment]
That sounds like an encoding issue … browserify only supports UTF-8 encoded files. There should be a setting in your editor to configure which encoding is used.
