### ISSUE TITLE
can work with node-gyp then use c++ code

### ISSUE THREAD

**Issue by Yongle-Fu** [browserify/browserify#1974]

**Comment by Yongle-Fu** [comment]
build/Release/xxx.node: Unexpected character '�' (1:0)

**Comment by ljharb** [comment]
You can't bundle C++ code into JS; it won't work in browsers.

**Comment by goto-bus-stop** [comment]
Right, if you're trying to use a C++ node module, you'll need to look for a non-C++ alternative. If you want to _write_ C++ and use it in the browser, you can look into [Emscripten](https://emscripten.org).
