### ISSUE TITLE
/standalone/concat-stream@latest 504 Gateway timeout

### ISSUE THREAD

**Issue by Dmeowmixer** [browserify/browserify#1976]
Using browserify CDN @latest, wzrd.in timeout with 504
`GET https://wzrd.in/standalone/whatwg-fetch@latest net::ERR_ABORTED 504`

Visiting `/standalone/concat-stream@latest` for testing results in 504 Gateway Timeout
![image](https://user-images.githubusercontent.com/8635238/89720527-c13f4300-d96e-11ea-9cfb-61969c225f23.png)

**Comment by ljharb** [comment]
That’s an issue with wzrd.in, not browserify.

**Comment by Dmeowmixer** [comment]
My bad!
