### ISSUE TITLE
test/crypto_ig.js error: Identifier 'Buffer' has already been declared

### ISSUE THREAD

**Issue by gabylb** [browserify/browserify#1977]
`npm test` of current latest browserify v16.5.2 fails in:

Subtest: test/crypto_ig.js
    # Subtest: crypto --insertGlobals
        1..2
Error: Parsing file /tmp/browserify/node_modules/asn1.js/lib/asn1/base/buffer.js: Identifier 'Buffer' has already been declared (6:6)

Same failure with Node.js v12.16.1 and v14.4.1 on Linux, and v14.9.0 on Windows.

It can be reproduced with:
```
git clone git@github.com:browserify/browserify.git
cd browserify
npm i
echo 'require("crypto")' > main.js
node bin/cmd.js main.js --ig
```
I can workaround the failure by commenting out this line:
const Buffer = require('safer-buffer').Buffer;
in:
node_modules/asn1.js/lib/asn1/decoders/pem.js
node_modules/asn1.js/lib/asn1/encoders/der.js
node_modules/asn1.js/lib/asn1/base/buffer.js

I didn't find this issue reported, so wondering if it's expected/known or an issue with my environment or Node.js version. 
Thanks in advance.

**Comment by goto-bus-stop** [comment]
Thanks, this should be fixed by in insert-module-globals@7.2.1 by https://github.com/browserify/insert-module-globals/commit/d86999f0180e09dd272666f5aff8db04183b3ea2.
