### ISSUE TITLE
promisify is not a function - util dependency version

### ISSUE THREAD

**Issue by acailly** [browserify/browserify#1978]
When I install a project, `util` dependecy version is `0.10.4` instead of a later version as allowed in package.json (`~0.12.0`) 

```
npm init -y
npm i browserify --save-dev
npm ls util
└─┬ browserify@16.5.2
  ├─┬ assert@1.5.0
  │ └── util@0.10.3 
  └── util@0.10.4 
```

I want to bundle `mkdirp` which uses `promisify` and since it is not in version `0.10.4`, i got the following error: `promisify is not a function`

I don't fully understand how npm dependency resolution works so I don't know if we can tell browserify to take a newest version.

Or maybe it is just me and you don't have this version issue? 

I will try to use `npm-force-resolutions` (https://github.com/rogeriochaves/npm-force-resolutions) but I hope there is a better solution :grin:

**Comment by acailly** [comment]
and I think I made a mistake, I was looking at `package.json` from the `master` branch which points to the `~0.12.0` version

but I see the `package.json` under the `16.5.2` tag points to the `~0.10.1` version

can you explain me why? :thinking:

**Comment by Raynos** [comment]
I think this is fixed on master but not published to npm.

**Comment by goto-bus-stop** [comment]
Finally released now in v17. Thanks!
