### ISSUE TITLE
How to output multiple files from directory?

### ISSUE THREAD

**Issue by gNesh01** [browserify/browserify#1979]
Hi,
I am using npm scripts and I would like all files in /src/****.js to be output in /dist/****.js 

`"browserify": "browserify -t babelify  src/*.js -o dist/*.js"`

This will output just 1 file. I know I can set multiple scripts for multiple files, BUT it would be great just to browserify:
`Every file in src directory > Same files in dist directory `

**Comment by goto-bus-stop** [comment]
`browserify src/*.js` will bundle all those files into a single bundle, and they will share dependencies and the like. They can't straightforwardly be output to a single file for each entry point. You have two options:
- browserify each file individually `browserify -t babelify src/a.js -o dist/a.js && browserify -t babelify src/b.js -o dist/b.js`
  This will give you standalone bundles for `a.js` and `b.js`.
- use [factor-bundle](https://github.com/browserify/factor-bundle) `browserify -t babelify src/a.js src/b.js -p factor-bundle [ -o dist/a.js -o dist/b.js ] -o dist/common.js`
  This will give you bundles `a.js` and `b.js`, that both depend on `common.js`: so you need to load `common.js` before you load either of the entry points.
