### ISSUE TITLE
Publishing new version to npm & help.

### ISSUE THREAD

**Issue by Raynos** [browserify/browserify#1981]
Hi browserify folks,

I see that the latest code in master has not been published to npm yet.

I'd love to help out with maintenance for browserify & watchify. I'm currently the `browserify` github org but don't have npm publish access.

Could you run the following ?

```
npm owner add raynos browserify
npm owner add raynos watchify
```

cc @goto-bus-stop @ljharb @feross

**Comment by goto-bus-stop** [comment]
I wanted to get [this](https://github.com/browserify/browserify/pull/1970) in before publishing v17 (there are some breaking changes in `master`). Just fixed the CI failure in [insert-module-globals@7.2.1](https://github.com/browserify/insert-module-globals/blob/master/CHANGELOG.md#721), so we should be able to get #1970 in after CI reruns there. I'll add you to the npm org!

**Comment by Raynos** [comment]
Thanks for publishing v17 !
