### ISSUE TITLE
How to bundle Third party node modules plugins and  use bundled script functions into another file using browserify

### ISSUE THREAD

**Issue by creativeDM** [browserify/browserify#1990]
Here is what i am looking for:-

theme.Js file import many third party node module scripts like this-
Import {bootstrap} from 'bootstrap/dist/js/bootstrap.bundle';

Import {AOS} from 'aos';
Import {Typed} from 'typed.js';

Above 3 plugins perfectly bundled in one file -theme.bundle.js

And of course included in html with script tag just before close body tag

Now i create another file for make aos animation to make work into my theme

custom/aos.js
Have code like

AOS.init();

My custom **aos.js** file i import into same file called - **theme.js**, after the modules imported

**Import './custom/aos.js'**

All custom and module scripts are now bundled well into **theme.bundle.js**

But when i open the html page into browser and its showing 
_reference error- AOS not defined_

Why it's showing this error?? I already import the aos module above the custom aos script

- Any help would be great

**Comment by goto-bus-stop** [comment]
Each module has its own scope for variables. Importing `aos` in one does not make it available in the other. You can store the variable on the global scope to make it available everywhere:

```js
// in theme.js
import {AOS} from 'aos';

// Allow anyone to access it
window.AOS = AOS;
```

Then anything that's loaded _after_ the above bundle can do:

```js
// in custom/aos.js
AOS.init();
```
