### ISSUE TITLE
Make browserify not bundle dependacies

### ISSUE THREAD

**Issue by Artrix9095** [browserify/browserify#1992]
So I'm trying to make my own module, that has 2 versions, the node version, and the browser version. In the node version, I use 2 dependencies, undici (a http library) and ws (Websocket connections), since I am only using the ws library for **connecting** i can do all this in the browser, since the browser has a builtin websocket and http library. I've already coded everything to make it support both, and when I try to compile, I notice I get some weird error abut browserify trying to compile undici and the module its using called "async_hooks". Once I saw this I looked around searching for a way to make browserify ignore dependencies but couldn't find any.
Help is appreciated and if this isn't added yet then I would hope it will be

**Comment by goto-bus-stop** [comment]
You can use the package.json [`"browser"` field](https://github.com/defunctzombie/package-browser-field-spec), this works in all major bundlers:
```json
{
  "browser": {
    "undici": false,
    "ws": false
  }
}
```

Then `require('undici')` and `require('ws')` will both evaluate to `undefined`, so you can provide your own alternative:
```js
var WebSocket = require('ws') || window.WebSocket
```
