### ISSUE TITLE
Bundle size too big because of stream-http

### ISSUE THREAD

**Issue by fireridlle** [browserify/browserify#1993]
Hello. I'm facing an issue that my bundle too heavy. I was trying to identify what is the biggest package/code and I found that it's stream-http and buffer.
```
npx browserify index.js --full-paths --debug | exorcist bundle.js.map > bundle.js
source-map-explorer --no-border-checks bundle.js bundle.js.map
```
![image](https://user-images.githubusercontent.com/12122603/106303171-7d186580-6262-11eb-8ba4-96134cf741fe.png)

None of them in package.json
```
"dependencies": {
    "abortcontroller-polyfill": "^1.7.1",
    "base64-js": "^1.2.0",
    "btoa-lite": "^1.0.0",
    "cross-fetch": "^3.0.6",
    "dotenv": "^8.2.0",
    "fn-annotate": "^1.1.3",
    "object-assign": "^4.1.0",
    "url-parse": "^1.4.7",
    "util-deprecate": "^1.0.2"
  }
```
However, I found that both stream-http and buffer are dependecies of browserify. Is there any solution to reduce bundle size?

**Comment by ljharb** [comment]
If any of your deps use node's `Buffer` or streams, then both of those deps are necessary and simply can't be omitted.

You can certainly avoid using Buffer/streams, or deps that use them, and then those browser polyfills would no longer be needed.

**Comment by fireridlle** [comment]
@ljharb thank you. is there any solution to override polyfills or disable them? 
i use http module inside condition like 
```
if(isNode) require('http')
```
so for browser i would like not to have stream-http polyfill

**Comment by goto-bus-stop** [comment]
You can use the [`"browser"` field](https://github.com/defunctzombie/package-browser-field-spec) in your package.json:
```json
{
  "browser": {
    "http": false
  }
}
```
Then `require('http')` will evaluate to `undefined`.
