### ISSUE TITLE
ParseError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by Isoaxe** [browserify/browserify#1998]
Hey guys,

I'm attempting to use Browserify to transpile some CommonJS code with `require('module')` statements to ES6 so the browser can understand. I've done this before, but this time there is the following error:

```
/Users/myName/Desktop/Git/myApp/node_modules/firebase/app/dist/index.esm.js:1
import firebase from '@firebase/app';
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

I've commented out the `require('firebase/app')` statement and replaced with a different module as a test in the same project file without changing any configurations and there is no problem. Seems to be affecting firebase only, possibly because it's the only `node_module` using `import` statements. 

Stuck on this for a while, any help would be much appreciated!

**Comment by goto-bus-stop** [comment]
looks like `firebase` has put an ES module in their `package.json` `"browser"` key… browserify does not support  ES modules.

You can use the [esmify](https://www.npmjs.com/package/esmify) plugin to transpile ES modules.

**Comment by Isoaxe** [comment]
Thanks for the quick answer! Yes that makes sense, though if Browserify is transpiling from CommonJS to ES I thought that any ES modules encountered would simply be ignored rather than converted to CommonJS and back again? I must be missing something here...

I tried what you said anyways, and ran into another error:
```
> browserify auth.js -p esmify > src/js/auth.js

internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module 'browser-resolve'
Require stack:
- /Users/lucas/Desktop/Git/Onit Landing/node_modules/esmify/resolve.js
- /Users/lucas/Desktop/Git/Onit Landing/node_modules/esmify/esmify.js
- /usr/local/lib/node_modules/browserify/index.js
- /usr/local/lib/node_modules/browserify/bin/args.js
- /usr/local/lib/node_modules/browserify/bin/cmd.js
```
So the `esmify` file `resolve.js` has a `require('browser-resolve')` statement at the top. I tried installing `browser-resolve` manually as a devDependency but just got a similar error, this time about `@babel/preset-env`. Feels wrong manually installing modules that I'm not directly using, any ideas?

**Comment by Isoaxe** [comment]
Even when I do install the two modules named in the sequential errors, I still get the following:
```
> browserify auth.js -p esmify > src/js/auth.js

Error: [BABEL] /Users/myName/Desktop/Git/myApp/node_modules/firebaseui/dist/esm.js: @babel/helper-compilation-targets: 'modules' is not a valid target
- Did you mean 'node'? (While processing: "/Users/myName/Desktop/Git/myApp/node_modules/@babel/preset-env/lib/index.js") while parsing file: /Users/myName/Desktop/Git/myApp/node_modules/firebaseui/dist/esm.js
```

**Comment by Isoaxe** [comment]
It turns out that the issue was being caused by a `babel.config` file that I had in place when attempting to resolve this issue via `babel` rather than `esmify`. Deleting the file resolved the issue.
