### ISSUE TITLE
Uncaught TypeError: exists is not a function

### ISSUE THREAD

**Issue by maxinepalmen1** [browserify/browserify#2000]
I am working on a project where I want to control my arduino in the browser, so I can change in-game features. However, when I try to incorporate my code in the browser I first got the error: Uncaught TypeError: require is not a function. So, I resolved this by using browserify to bundle. However, when I used browserify I now get the error: Uncaught TypeError: exists is not a function. Can anyone help me to work around this error?

My code is the following:
Electronic.js
````
var five = require("johnny-five");

var slider = 0;

var board = new five.Board();

board.on("ready", function() {

    slider = new five.Sensor("A0");

    slider.on("data", function() { // "data" get the current reading from the potentiometer

    console.log(this.value);

    var value = this.value;       
  });
});`
```


HTML code:
```
`<html>

<body>
	<div id= "result">

	</div>
	<script src="browse.js"></script>
</body>

</html>`
```

browse.js is the browsified code of electronic.js

**Comment by ljharb** [comment]
What node version are you using? Can you share the entire stack trace?

**Comment by maxinepalmen1** [comment]
I am using Node version v14.16.0

**Comment by maxinepalmen1** [comment]
What do you exactly mean with the stack trace (I am new to this)

**Comment by ljharb** [comment]
The full contents of the error message, which includes filenames and line numbers.

**Comment by ljharb** [comment]
One likely possibility is that this is meant to be `fs.exists`, but there's no filesystem in the browser. It's highly likely that johnny-five is fundamentally incompatible with the browser (since it's meant to run on an arduino).

**Comment by maxinepalmen1** [comment]
`
Uncaught TypeError: exists is not a function
    at Function.getRoot (browse.js:12331)
    at bindings (browse.js:12210)
    at Object.55../legacy (browse.js:9445)
    at o (browse.js:1)
    at browse.js:1
    at Object.<anonymous> (browse.js:9309)
    at Object.<anonymous> (browse.js:9312)
    at Object.52../darwin (browse.js:9312)
    at o (browse.js:1)
    at browse.js:1
`

**Comment by ljharb** [comment]
That strongly implies to me what I described in https://github.com/browserify/browserify/issues/2000#issuecomment-803043770.

**Comment by maxinepalmen1** [comment]
yeah I want to run the arduino with javascript and use the input from the arduino sensor in the web browser's game but I don't know how to do that

**Comment by maxinepalmen1** [comment]
You mean that I need to change the exists to fs.exists?

**Comment by ljharb** [comment]
No - what I mean is, it's impossible to do that directly from the browser. You need to have a webserver as a proxy between the arduino and the browser.

**Comment by maxinepalmen1** [comment]
ah ok. Do you know a way how I can do that?

**Comment by ljharb** [comment]
You'd have to set up your own webserver. I'd suggest using `express`; I'm sure there's a bunch of tutorials you can google for how to set up a basic website - it depends very highly on what UI you want in the browser, what capabilities you want to expose with the server, and on your experience setting up web apps.

Since this isn't a browserify issue, is it ok to close this?

**Comment by maxinepalmen1** [comment]
so is it possible to control the game radius raid (also open source code of github) with the sliders? via express and johnny-five?

**Comment by maxinepalmen1** [comment]
I am completely stuck at the fact that I don't know how to use the output of my slide potentiometer to a js file running on the web.

**Comment by ljharb** [comment]
Anything you can use node to do, you can indirectly control from a browser via node that hosts a website.

I’m not sure how to explain it any better on GitHub. You may want to find an irc/slack/discord channel where you can ask, since real-time chat will likely be more effective.
