### ISSUE TITLE
client server connection for node.js

### ISSUE THREAD

**Issue by maxinepalmen1** [browserify/browserify#2001]
At the moment, I am working on a project where I want to use the output data of a slide potentiometer (Arduino Uno) to control the features of a game running on the server. In my command prompt I can see the live data of the slide potentiometer which is a good first step. However, as I understood node.js will not run on the server. Therefore, I need to make a client-server connection to use the sensor data into the js files running on the server. Nonetheless, I cannot get this to work. Can anyone please help me?

**Comment by ljharb** [comment]
This is a better question for StackOverflow, or a community on irc/slack/discord.
