### ISSUE TITLE
Uncaught Error: Cannot find module 'fs-extra'

### ISSUE THREAD

**Issue by cs17b027** [browserify/browserify#2007]
My code is compiled without error but it's giving an error while running.

I'm using var fs = require('fs-extra');
installed using npm i fs-extra

can you please tell me the reason why it's happening

**Comment by ljharb** [comment]
You can't bundle things that touch the filesystem, because there's no filesystem in the browser.

**Comment by PanagiotisDrakatos** [comment]
@ljharb  I resepect your experience and i need your help i am facing a similar issue with another module node-java.

% npm install -g browserify
% . ~/.bash_profile
% npm install --save java
% browserify src/java.js -p esmify --standalone mybundle > bundle.js

This is the java.js file
```
#!/usr/bin/env node
const java = require("java");
function myfunc2() {
    java.classpath.push(__dirname +"/adrestus-crypto-1.0-SNAPSHOT-jar-with-dependencies.jar")
    var mnemonic = "example1";
    var passphrase = "pass";
    var result = java.callStaticMethodSync("io.Adrestus.crypto.WalletAddressExport", "getAddressFromMnemonic", mnemonic, passphrase);
    return result;
}
module.exports = {
    myfunc2,
};
```
When i load the bundle from html code i got this error 

`Uncaught Error: Cannot find module '/node_modules/java/build/Release/nodejavabridge_bindings.node'`

Does my module also not supported with browserfy or its something different? what are your thoughts?

**Comment by ljharb** [comment]
@PanagiotisDrakatos please don't cross-post; this was answered in another thread. `.node` files are native code and can't ever work in a browser, and it's a reasonable assumption that anything with "java" in the name (that's not "javascript", ofc) also can't ever work in a browser.

**Comment by houd1ni** [comment]
@ljharb why don't close these stale and answered long time ago issues ?

**Comment by ljharb** [comment]
@houd1ni usually it's nice to wait awhile to see if the OP responds.

In this case, sure, it can be closed.
