### ISSUE TITLE
Bundle Code Into Library with usable functions

### ISSUE THREAD

**Issue by Quantalabs** [browserify/browserify#2012]
I'm trying to use browserify to bundle all my dependencies together and my code, but also have all the functions usable when imported. This way it can be distributed through JSDelivr or unpkg or another CDN and the functions and classes can be used, but, when I run:
```sh
browserify EpiJS -o web/index.js
```
and then import it:
```html
<script src="web/index.js"></script>
<script>
...
</script>
```
none of the functions are usable. Is there a way to use browserify to bundle all the dependencies together and have usable functions?

**Comment by Quantalabs** [comment]
I found:
```sh
browserify module.js --s module > bundle.js
```
Just wondering, are there any alternatives?

**Comment by goto-bus-stop** [comment]
You can export your functions to the global object using
```js
function libraryFunction () {
  // your stuff here
}

window.libraryFunction = libraryFunction
```
