### ISSUE TITLE
Uncaught TypeError: _os.constants is undefined

### ISSUE THREAD

**Issue by KalaikoJuzo** [browserify/browserify#2041]
Hey, I built a bundle of my main.js that uses require()s for fs and youtube-dl-exec modules but I have the  following error when I load the html page in my browser :
Uncaught TypeError: _os.constants is undefined
Can you help me ?

**Comment by goto-bus-stop** [comment]
youtube-dl-exec needs to execute a child process in the browser, which is impossible. You cannot use those modules in the browser with any bundler.

**Comment by Kali95739** [comment]
Yes u can liar lol
