### ISSUE TITLE
How to get access to external module?

### ISSUE THREAD

**Issue by Futyn-Maker** [browserify/browserify#2044]
Hello!

Don't understand how can I get access to external modules bundled with Browserify from web. I'm trying to write a module that can be used both in node and in browser.

`convert.js`:

```javascript
const jschardet = require("jschardet");
const iconv = require("iconv-lite");

function convert(inText) {
    ...
    return outText;
}

module.exports = convert;
```

Then I do:
`browserify convert.js > convert.min.js`

`index.html`:

```
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<script src="./convert.min.js"></script>
</head>

<body>
<script>
console.log(convert('CONVERT ME!'); // ReferenceError
</script>
</body>
</html>
```

How can I get access to `convert` function from my HTML-file or other connectet JS?

Thanks!

**Comment by ljharb** [comment]
@Futyn-Maker generally, you browserify your app's entry point. You can use `--standalone` if you want to export something globally.
