### ISSUE TITLE
‘browserify in the wild’ product link appears been hijacked

### ISSUE THREAD

**Issue by tylermneher** [browserify/browserify#2045]
The # @[RequireBin.com](http://requirebin.com/) link on the [browserify in the wild](https://github.com/browserify/browserify/wiki/browserify-in-the-wild#requirebincom) page appears to have been hijacked and no longer resolves to the product as described.

**Comment by mikixing** [comment]
您的邮件我已收到，会尽快查阅~

**Comment by goto-bus-stop** [comment]
addressed in https://github.com/browserify/browserify-website/commit/8a2ee055596d7877a34feb2d4bbadd4717cf9f1d. thanks!
