### ISSUE TITLE
bundled file can't read 'undefined' (prototype)

### ISSUE THREAD

**Issue by aizyuval** [browserify/browserify#2047]
Hi, 

**Pre-bundled file includes:**
```
import {express} from 'express';
const app = express();
// express functionalities...
```

**Bundling via:** `browserify ./src/background.js > bundle.js -t babelify`

When running it on the browser the bundled file raise an error: `Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')`
In this line -> `var res = Object.create(http.ServerResponse.prototype)`

Browserify and node are running in their latest versions.

What am I missing?
Yuval

**Comment by goto-bus-stop** [comment]
express cannot be run in the browser.
