### ISSUE TITLE
Archive this repository

### ISSUE THREAD

**Issue by akirataguchi115** [browserify/browserify#2065]
Hey there, @goto-bus-stop ! Could we archive this repository so that people would know this is abandoned?

**Comment by ljharb** [comment]
It’s not abandoned.

**Comment by akirataguchi115** [comment]
Ah my bad then. Could you point out then how is this project maintained? Maybe reopen this issue with different title f.ex "Describe maintain status"?

**Comment by akirataguchi115** [comment]
Usually projects that are not maintained are just archived or removed from npm to avoid confusion.

Browserify seems to have some dependency deprecation and doesn't do the job well enough than f.ex. esbuild. Also the latest merged commit seems to be from 2022 March. Is there some other maintenance happening behind the scenes that I'm not aware of?

**Comment by ljharb** [comment]
Deprecated deps aren't inherently a problem, and your subjective opinion of how well a tool "does the job" isn't relevant to whether a project is maintained or not.

"Maintained" also is not directly tied to commit recency or frequency.

**Comment by akirataguchi115** [comment]
I see. Thanks for the insights! How would you define "maintained" then?

**Comment by ljharb** [comment]
There's no universal definition - but if someone is responding to issues in a reasonable time frame, and in particular, is available to address/triage potential security vulnerabilities, then I'd say it's maintained.
