### ISSUE TITLE
ERROR in ./node_modules/ ... in ReactJs

### ISSUE THREAD

**Issue by khai732003** [browserify/browserify#2072]
Hi, I have a problems with my project now.

Compiled with problems:
×
ERROR in ./node_modules/buffer-equal-constant-time/index.js 4:13-37
Module not found: Error: Can't resolve 'buffer' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\buffer-equal-constant-time'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }
ERROR in ./node_modules/jsonwebtoken/sign.js 16:4-21
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jsonwebtoken'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
ERROR in ./node_modules/jsonwebtoken/verify.js 13:4-21
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jsonwebtoken'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
ERROR in ./node_modules/jwa/index.js 3:13-30
Module not found: Error: Can't resolve 'crypto' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "crypto": require.resolve("crypto-browserify") }'
	- install 'crypto-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "crypto": false }
ERROR in ./node_modules/jwa/index.js 5:11-26
Module not found: Error: Can't resolve 'util' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jwa'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }
ERROR in ./node_modules/jws/lib/data-stream.js 3:13-30
Module not found: Error: Can't resolve 'stream' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }
ERROR in ./node_modules/jws/lib/data-stream.js 4:11-26
Module not found: Error: Can't resolve 'util' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }
ERROR in ./node_modules/jws/lib/sign-stream.js 5:13-30
Module not found: Error: Can't resolve 'stream' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }
ERROR in ./node_modules/jws/lib/sign-stream.js 7:11-26
Module not found: Error: Can't resolve 'util' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }
ERROR in ./node_modules/jws/lib/tostring.js 2:13-37
Module not found: Error: Can't resolve 'buffer' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }
ERROR in ./node_modules/jws/lib/verify-stream.js 5:13-30
Module not found: Error: Can't resolve 'stream' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "stream": require.resolve("stream-browserify") }'
	- install 'stream-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "stream": false }
ERROR in ./node_modules/jws/lib/verify-stream.js 7:11-26
Module not found: Error: Can't resolve 'util' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\jws\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "util": require.resolve("util/") }'
	- install 'util'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "util": false }
ERROR in ./node_modules/safe-buffer/index.js 3:13-30
Module not found: Error: Can't resolve 'buffer' in 'C:\Users\DLCT\Desktop\SWP.CAGE.github.io\productPagee\node_modules\safe-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }
=========================================================

IN App.js

import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import ProductPage from './SanPham/ProductPage';
// import ContactPage from './components/ContactPage';
import { CartProvider } from './SanPham/Context/CartContext';
import Navigation from './SanPham/Navigation/Navigation';
import {
  Routes,
  Route,
} from "react-router-dom";

import Order from "./SanPham/Order";
import VNPayPayment from './SanPham/VNPayPayment';
import Login from './SanPham/Login';
import Register from './SanPham/Register';
import { AuthProvider } from './SanPham/Context/AuthContext';

function App() {
  return (
    <div className="App">
      <AuthProvider>
        <CartProvider>
          <Navigation />
          <Routes>
            <Route path="/register" element={<Register />} />
            <Route path="/login" element={<Login />} />
            <Route path="/" element={<ProductPage />} />
            <Route path="/order/:orderId" element={<Order />} />
            <Route path="/payment/:orderId" element={<VNPayPayment />} />
          </Routes>
        </CartProvider>
      </AuthProvider>

    </div>
  );
}

export default App;

And then I comment AuthProvider like that:

import React from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
import ProductPage from './SanPham/ProductPage';
// import ContactPage from './components/ContactPage';
import { CartProvider } from './SanPham/Context/CartContext';
import Navigation from './SanPham/Navigation/Navigation';
import {
  Routes,
  Route,
} from "react-router-dom";

import Order from "./SanPham/Order";
import VNPayPayment from './SanPham/VNPayPayment';
import Login from './SanPham/Login';
import Register from './SanPham/Register';
import { AuthProvider } from './SanPham/Context/AuthContext';

function App() {
  return (
    <div className="App">
      <AuthProvider>
        <CartProvider>
          <Navigation />
          <Routes>
            <Route path="/register" element={<Register />} />
            <Route path="/login" element={<Login />} />
            <Route path="/" element={<ProductPage />} />
            <Route path="/order/:orderId" element={<Order />} />
            <Route path="/payment/:orderId" element={<VNPayPayment />} />
          </Routes>
        </CartProvider>
      </AuthProvider>

    </div>
  );
}

export default App;

It's not any problems?

In AuthContex.js
import React, { createContext, useContext, useEffect, useState } from "react";
import jwt from "jsonwebtoken"; // Import thư viện jsonwebtoken

const AuthContext = createContext();

export const useAuth = () => {
    return useContext(AuthContext);
};

export const AuthProvider = ({ children }) => {
    const [user, setUser] = useState(null);

    useEffect(() => {
        const token = localStorage.getItem('token');
        if (token) {

            setUserFromToken(token);
        }
    }, []);

    const setUserFromToken = () => {
        try {
            const secretkey = "my-secretket.."

            const storedToken  = localStorage.getItem('token');

            const decodedToken = jwt.verify(storedToken , secretkey);
            console.log("Decoded Token:", decodedToken);
            // Lưu thông tin người dùng vào state user
            setUser(decodedToken);
        } catch (error) {
            // Xử lý lỗi nếu token không hợp lệ
            console.error("Error decoding token:", error);
            // Đặt user về null hoặc thực hiện các xử lý khác tùy thuộc vào yêu cầu của bạn
            setUser(null);
        }
    };
    

    return (
        <AuthContext.Provider value={{ user, setUserFromToken }}>
            {children}
        </AuthContext.Provider>
    );
};

Actually they can use 2 nested providers right =((( 
Pls help me =((((

**Comment by mikixing** [comment]
您的邮件我已收到，会尽快查阅~

**Comment by Abdullah-03** [comment]
Why are you raising a webpack issue in browserify repo?
