### ISSUE TITLE
Where do I put flags in config?

### ISSUE THREAD

**Issue by blaasvaer** [browserify/browserify#2076]
I'm trying to make Browserify ignore dynamic imports (what a nightmare) by trying to add the --ignore-missing flag (found in the docs).

Now, WHERE in this (package.json) entry do I put this flag?

```
  "browserify": {
    "options": {
      "browserifyOptions": {
        "paths": [
          "./node_modules",
        ]
      }
    }
  }

```

**Comment by davmillar** [comment]
@blaasvaer it looks like you'll want to specify it as `ignoreMissing: true` in your `browserifyOptions` config object.
