### ISSUE TITLE
global modules with debug source maps

### ISSUE THREAD

**Issue by foobar8675** [browserify/browserify#617]
Hello, 

I'm trying to run a script from webstorm to build the bundle with debug source maps and one of the modules public.  I used to only run the first line below to generate the source maps and it worked fine. However, now that I need a global module, I'm a bit stumped. Any help is appreciated
# !/bin/sh

browserify --entry main.js --outfile bundle.js --debug
browserify -r ./setup.js > bundle.js

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant.
