### ISSUE TITLE
requiring an alias module returns an empty object

### ISSUE THREAD

**Issue by abernier** [browserify/browserify#751]
Hi,

I don't know if this is really a bug, but at least this is an issue for me...

When giving an alias `Myapp` for my main script `src/index.js`, ie:

``` sh
./node_modules/.bin/browserify -r ./src/index.js:Myapp
```

then, if I try to `require('Myapp')` somewhere else, it returns an empty object `{}` rather than my expected `Myapp` constructor

NB : `Myapp` constructor is correctly exported in `src/index.js`, ie:

``` js
function Myapp() {
  alert('hi new myapp instance!')
}

exports.Myapp = Myapp;
module.exports = Myapp;
```

Can you confirm it's a bug ?

Thank you

**Comment by goto-bus-stop** [comment]
looks like it's been fixed sometime in the past 3½ years—please reopen if not
