### ISSUE TITLE
Allow browserify to search up for package.json

### ISSUE THREAD

**Issue by knownasilya** [browserify/browserify#775]
Currently if using the browserify API, say in a `gulpfile.js` in a directory below the `package.json` directory, you get errors because it never finds those configurations.

Maybe it would be a good idea to use @thlorenz's [mothership](https://github.com/thlorenz/mothership) module.

Or maybe adding an option to the API like `packageJsonPath`..

**Comment by terinjokes** [comment]
It looks like `module-deps` does search up the path for a package.json file, https://github.com/substack/module-deps/blob/ba19c56390910a30da2d526908adea7c9e074f40/index.js#L445. Can you create a simple reproducible case?

**Comment by knownasilya** [comment]
Well this was like a year ago, so it might have been fixed since then?
