### ISSUE TITLE
idea: pull out !node logic

### ISSUE THREAD

**Issue by juliangruber** [browserify/browserify#797]
Create a module like `commonjsify` that is like browserify would have been if it only emulated a commonjs environment. Or call it `npmify`. No implicit `Buffer`, `process` etc. Basically only the module system, transforms and all the other !node things.

Then, refactor browserify to use that module and add all the node stuff.

I've come to this idea working with component and liking that it's not emulating an environment but rather leaving you with an empty slate, without any (node) compatibility features.

Afaik browserify is already going that direction, recommending to require node core modules from npm with explicit versioning, instead of relying on the versions bundled with browserify.

**Comment by goto-bus-stop** [comment]
I think this is addressed by `--bare` and `opts.bare` exists now too.
