### ISSUE TITLE
Trouble with libs that require('readable-stream/transform')

### ISSUE THREAD

**Issue by gobengo** [browserify/browserify#810]
See these two links
https://github.com/rvagg/through2/pull/20
https://github.com/gobengo/chronos-stream-dependant

Can someone tell me how they are currently using readable-stream in node and streams>=2 in the browser with browserify 0.4.2?

through2 seems like a very popular lib but I couldn't get it working without the pull above.

Specifically
- through2 requries Transform like `require('readable-stream/transform')` as opposed to `require('readable-stream').Transform`
- I couldn't come up with any values for package.json browser key that would make that require work
- All the would work is switching to `require('readable-stream').Transform` and using the browser hash to map 'readable-stream' to 'stream-browserify'

Thanks for your collective wisdom.

**Comment by goto-bus-stop** [comment]
Seems to have been fixed sometime in the past 3½ years. thanks!
