### ISSUE TITLE
streams : wrong dependencies execution order

### ISSUE THREAD

**Issue by dduponchel** [browserify/browserify#815]
With the following test.js file :

``` js
var stream = require('readable-stream');
console.log(stream.Transform.prototype.on);
```

In nodejs, I get the expected `[Function]` loggued.
I then use browserify :

``` sh
$ browserify --version
4.2.0
$ browserify test.js -o bundle.js -s bundle
```

In a browser (tested with Firefox 30 and Chromium 35), I get `undefined`.

In the generated bundle.js file, if I add a log for each interesting `inherits` call, I get :

```
Stream inherits EventEmitter
Writable inherits Stream
Duplex inherits Readable
Transform inherits Duplex
PassThrough inherits Transform
Readable inherits Stream          // <- too late !
```

The Readable class inherits Stream too late, and the other classes don't get its methods (like `on`).

**Comment by goto-bus-stop** [comment]
Seems to have been fixed sometime in the past 3½ years. thanks!
