### ISSUE TITLE
browserify opts.basedir isn't global

### ISSUE THREAD

**Issue by adam-lynch** [browserify/browserify#848]
Is this expected?

I assumed that if you pass a `basedir` then you can require `./x` from anywhere and it'll work if `x` exists at the `basedir`. It doesn't seem to do at all for me. For me, it just effects the paths you pass to `browserify`.

Before: 

``` coffeescript
browserified = browserify './src/hello.coffee',
    extensions: ['.coffee']

browserified.transform coffeeify,
    global: true

browserified.bundle
    extensions: ['.coffee']
```

After: 

``` coffeescript
browserified = browserify './hello.coffee',
    extensions: ['.coffee']
    basedir: './src'

browserified.transform coffeeify,
    global: true

browserified.bundle
    extensions: ['.coffee']
```

(If `src` isn't removed from the entry file path then an error is thrown that `./src/hello.coffee` can't be found from `./src`)

---

browserify: `4.2.1`
node: `0.10.20`
npm: `1.3.11`
windows: `8.1`

**Comment by goto-bus-stop** [comment]
indeed, expected behaviour (closing some old issues)
