### ISSUE TITLE
add(file) and require(fil) does not support arrays anymore

### ISSUE THREAD

**Issue by torarnek** [browserify/browserify#859]
This used to work:
var b = browserify();
b.add(["foo.js","bar.js"];
b.require(["foo.js","bar.js"];

It fails with: Error: path must be a string

Version: 5.9.3

Full stack:
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: path must be a string
    at /Users/torkvalo/oppdrag/app-main/web/node_modules/browserify/node_modules/resolve/lib/async.js:15:16
    at process._tickCallback (node.js:419:13)

**Comment by goto-bus-stop** [comment]
this works as of `14.5.0`
