### ISSUE TITLE
Is there a way to set fullPaths: true in package.json ?

### ISSUE THREAD

**Issue by AlexRiedler** [browserify/browserify#870]
the browserify-shim transform needs the fullpaths to do resolution of lookups, and in v5 fullPaths needs to be true... is there a way to set this up automatically from package.json or similiar?

related issue: https://github.com/thlorenz/browserify-shim/pull/83

**Comment by goto-bus-stop** [comment]
this seems to no longer be a problem for browserify-shim. please open a new issue if it is still relevant
