### ISSUE TITLE
transforms with `global: true` break with files matching /@.*global/

### ISSUE THREAD

**Issue by shawninder** [browserify/browserify#894]
The code that follows behaves as expected. I will then show the various ways that break it. That is where strangeness appears.

**index.js**

```
var browserify = require('browserify')
  , through = require('through')
  , b = browserify('./a.js')

b.transform({ global: true }, function (file) {
  if(file.indexOf('.less') !== -1){
    console.log('ignoring ' + file)
    return through(write, end);

    function write (buf) {
      // NOTHING
    }
    function end () {
      this.queue(null)
    }
  }
  return through()
})

b.bundle(function (err, src) {
  if (err) {
    console.error('ERROR', err)
  }
})
```

**a.js**

```
require('./styles.less')
```

**styles.less**

```
global
```

`node index.js` correctly prints "ignoring .../styles.less". If any of the following modifications are made however, an error is printed instead:
- In _styles.less_, replace `global` with `@global`
- In _styles.less_, replace `global` with `@\nglobal`
- In _styles.less_, replace `global` with `@whatever [...] global`
- ...

In every case, the error says `SyntaxError: Line 2: Unexpected token ILLEGAL while parsing .../styles.less while parsing file: .../styles.less`

In every case, one can get expected behaviour again by removing `{ global: true }` from _index.js_.

**Comment by goto-bus-stop** [comment]
fixed in https://github.com/browserify/browserify/commit/aa84e4712d041ef26854fd35d69eccbdcaf87ed6. thanks!
