### ISSUE TITLE
Invalid Package: expected node-browserify but found browserify 

### ISSUE THREAD

**Issue by mattlinares** [browserify/browserify#903]
browserify installed, not sure what's up here. Can you help?

~/code/ethereum/ethereumjs-lib> npm install
npm ERR! Error: Invalid Package: expected node-browserify but found browserify
npm ERR!     at /usr/lib/node_modules/npm/lib/cache/add-local-tarball.js:161:14
npm ERR!     at process._tickCallback (node.js:419:13)
npm ERR! If you need help, you may report this _entire_ log,
npm ERR! including the npm and node versions, at:
npm ERR!     http://github.com/npm/npm/issues

npm ERR! System Linux 3.13.0-35-generic
npm ERR! command "node" "/usr/bin/npm" "install"
npm ERR! cwd /home/code/ethereum/ethereumjs-lib
npm ERR! node -v v0.10.30
npm ERR! npm -v 1.4.27
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/code/ethereum/ethereumjs-lib/npm-debug.log
npm ERR! not ok code 0

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant
