### ISSUE TITLE
RangeError and infinitely recursing parse errors

### ISSUE THREAD

**Issue by atombender** [browserify/browserify#911]
Using 3.46.1 with `envify` and `reactify`. Our app has an endpoint that dynamically compiles a JS file with Browserify, and randomly it will get into a state where compiling doesn't work. It can happen after running the app for a day, or a week. Here's what it does:

``` javascript
      browserify({extensions: ['.jsx']})
        .require(path.join(root, 'app/bundles/widgets'), {
          entry: true,
          basedir: path.join(root, 'app')
        })
        .transform('reactify')
        .transform('envify')
        .bundle({debug: false}, function(err, src) {
          if (!err) {
            if (!development) {
              src = minify(src);
            }
            memcached.set(cacheKey, src, CACHE_TTL, function(err) {
              if (err) {
                console.error("Could not cache widget bundle", err);
              }
            });
          }
          callback(err, src);
        });
```

and here is the `err` when printed (word-wrapped for readability):

```
RangeError: Parse Error: Parse Error: Parse Error:
Parse Error: Parse Error: Parse Error: Parse Error:
Parse Error: Parse Error: Parse Error: Parse Error:
Parse Error: Parse Error: Parse Error: Parse Error:
Parse Error: Parse Error: Parse Error: Parse Error:
Parse Error: Parse Error: Parse Error: Parse Error:
Parse Error: Parse Error: Parse Error: Parse Error:
Parse Error: Parse Error: Parse Error: Parse Error:
[... lots more ...]
Parse Error: Maximum call stack size exceeded
```

Of course, that's not very helpful.

Restarting the app resolves the issue.

Have done `strace` on the process and its threads, but it doesn't reveal anything out of the ordinary. 

I do have a running process right now that is currently broken, and I have left it running so I can debug more closely. Is there a trick I can use to get more information from the process?

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one with a reproduction if this is still relevant
