### ISSUE TITLE
Ability to completely switch off builtins

### ISSUE THREAD

**Issue by drewnoakes** [browserify/browserify#925]
I have a TypeScript project from which AMD modules were being compiled for use with RequireJS. I'm considering compiling CommonJS modules and using Browserify.

I became stuck due to builtins. Specifically, they collide with my existing modules, such as `constants` and `util`.

(Note that I'm bundling using Gulp and therefore the API, not the command line)

The documentation didn't make things too clear, but from reading the source code ([index.js#364](https://github.com/substack/node-browserify/blob/master/index.js#L364)) I learned that even if I set `options.builtins` to `{}` or `false`, then exclusions are still made for the set of builtins in `lib/builtins.js`.

What I want is the ability to **completely disable builtins**. I don't use any node packages, and worse, they are causing my application to fail as my modules are not loaded.

It seems the only way to do what I want is to write something like:

```
return browserify('main.js', {
        basedir: './scripts/app/',
        paths: ['./scripts/app/'],
        builtins: {assert:null,buffer:null,child_process:null,cluster:null,console:null,constants:null,crypto:null,dgram:null,dns:null,domain:null,events:null,fs:null,http:null,https:null,module:null,net:null,os:null,path:null,punycode:null,querystring:null,readline:null,repl:null,stream:null,_stream_duplex:null,_stream_passthrough:null,_stream_readable:null,_stream_transform:null,_stream_writable:null,string_decoder:null,sys:null,timers:null,tls:null,tty:null,url:null,util:null,vm:null,zlib:null,_process:null}
    })
```

Obviously this is quite ugly.

I'm happy to make a PR for this, but want to understand if there's an alternative approach to achieve this, or some reason that it would be be accepted into the library.

Would what I'm asking be covered by the [`--no-builtins`](https://github.com/substack/node-browserify/blob/master/bin/advanced.txt#L33) command line flag, or is that something else?

Essentially the entire builtins block could be wrapped to resemble:

```
if (opts.noBuiltins === true) {   // <-- new option
    if (opts.builtins === false) {
        mopts.modules = {};
        self._exclude.push.apply(self._exclude, Object.keys(builtins));
    }
    else if (opts.builtins && isarray(opts.builtins)) {
        mopts.modules = {};
        opts.builtins.forEach(function (key) {
            mopts.modules[key] = builtins[key];
        });
    }
    else if (opts.builtins && typeof opts.builtins === 'object') {
        mopts.modules = opts.builtins;
    }
    else mopts.modules = builtins;

    Object.keys(builtins).forEach(function (key) {
        if (!has(mopts.modules, key)) self._exclude.push(key);
    });
}
```

**Comment by stefanbuck** [comment]
@drewnoakes for me it works fine.

```
browserify({
        builtins: false
    })
    .require(sourcePath)
    .bundle()
    .pipe(fs.createWriteStream(bundlePath));
```

**Comment by goto-bus-stop** [comment]
yeah, --no-builtins is equivalent to --builtins=false which is equivalent to `builtins: false` in the api. please comment if that doesn't help.
