### ISSUE TITLE
Entry file cannot be dependency?

### ISSUE THREAD

**Issue by milesburton** [browserify/browserify#932]
Hello,

I've run across a rather unusual side effect which I'm trying to determine whether it is related to my project or if it's actually a bug.

If you specify two entry points. One of which is a dependency of one entry points the resulting module is set to undefined.

./foo.js

``` js
require('./libs/bar.js');
require('./libs/baz.js');

module.exports = {"file": "foo.js"}
```

./libs/bar.js

``` js
module.exports = {"file": "bar.js"};
```

./libs/baz.js

``` js
require('./bar.js');

{"file": "baz.js"}
```

When browerify configuration is

``` js
{
entries: [
"./foo.js",
"./libs/bar.js"
]
}
```

The result is:

Error: Cannot find module './libs/bar.js'

and within the bundled file:

"./libs/bar.js":undefined,

...even though bar.js has been bundled and given an appropriate ID.

**Comment by goto-bus-stop** [comment]
still exists. this is a bug in module-deps:

```
$ module-deps foo.js lib/bar.js
[
{"file":"/tmp/repro-browserify-932/lib/bar.js","id":"/tmp/repro-browserify-932/lib/bar.js","source":"module.exports = {\"file\": \"bar.js\"};","deps":{},"entry":true}events.js:137
      throw er; // Unhandled 'error' event
      ^
Error: Cannot find module './libs/bar.js' from '/tmp/repro-browserify-932'
```

it is thrown by `resolve`, so i think module-deps gives it the wrong `basedir`.

**Comment by goto-bus-stop** [comment]
I actually made a mistake in the test, can't reproduce now. There are still similar issues in #1260 and #1068. Please open a new issue if this does come up again.
