### ISSUE TITLE
How to debug in browsers that don't support source maps?

### ISSUE THREAD

**Issue by mightyiam** [browserify/browserify#936]
Hi and thank you very much for Browserify!

What I'm missing is something that will make debugging easier when browsers do not support source maps.

I debug with IE8+ and in the first case where it fails with an error on my code, I can't seem to debug properly because it doesn't let me insert a breakpoint on the browserified source file, saying that it "isn't loaded" or something.

All newer browsers don't have such a issue. Perhaps this is only a file size thing? Perhaps something else.

I realize that this may not be the case, but, perhaps, if there was a way to browserifying without concatenating, perhaps that will work around my issue.

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant.
