### ISSUE TITLE
opts.externalRequireName does not work in standalone mode

### ISSUE THREAD

**Issue by ibc** [browserify/browserify#972]
I use grunt-contrib-browserify as follows:

```
browserify: {
    dist: {
        files: {
            'builds/mystuff-bundle.js': [ 'lib/MyStuff.js' ]
        },
        options: {
            browserifyOptions: {
                externalRequireName: '__reqqq__',
                standalone: 'MyStuff'
            }
        }
    }
},
```

The `externalRequireName` does nothing as I still see `require` calls within the bundled file. Should it work? I've also tested that it does nothing when the `standalone` option is NOT set. Should I assume it is a bug in the grunt-contrib-browserify package?

I expect that the `externalRequireName` option should replace `require()` by other name, so I do not need hacks like `derequire()`, am I right?

**Comment by goto-bus-stop** [comment]
`externalRequireName` only affects the name of a public global `require()` function that can be used to require modules inside the bundle, from elsewhere on the page. it does not affect the way modules inside the bundle call `require`. use [derequire](https://github.com/calvinmetcalf/derequire) to change the name used for require function calls inside the bundle.
