### ISSUE TITLE
require() paths in production build

### ISSUE THREAD

**Issue by newtonianb** [browserify/browserify#974]
I have a file `app.js` that contains the following

```
require('../../components/migrate-1.2.1.min.js');
require('../../components/backjs');
require('../../components/hover.js');
```

These paths are still visible in the final compiled app.js as it seems to be used as the key for the code block in the require?
1. How can I clean these paths? I don't want to reveal my entire back-end folder structure
2. I'm trying to copy the **compiled** app.js and use it independently of browserify in another project (essentially just load it as a JS library bundle) is that suppose to work? I don't know why I just can't get it working in the separate project when I include the compiled app.js, I keep getting some funky errors about could not load module. Any idea what's going on?

I thought the compiled JS file should have everything it needs within itself?

**Comment by yamalight** [comment]
Hi there, @newtonianb
I made a gulp plugin that shortens the names for production, you can find it here: https://github.com/yamalight/gulp-browserify-mangle - is that what you wanted in 1)?

**Comment by goto-bus-stop** [comment]
Cleaning up old issues, please open a new one if this is still relevant.
