### ISSUE TITLE
Requiring a file which was bundled with bower fails with unmet dependencies

### ISSUE THREAD

**Issue by EgoAleSum** [browserify/browserify#978]
In our project we're including a library that's been bundled with bower: Rosso.js ( https://github.com/EgoAleSum/Rosso.js ).<br>The library is installed via bower and the source is in `/Users/Alessandro/ui/bower_components/rosso`.

The code that includes the Rosso.js file is just `require('bower_components/rosso/Rosso.js')`, with `Rosso.js` being the "compiled bundle".

However, while running browserify, I get the following error:

```
$ browserify main.js -o public/js/app.js
Error: Cannot find module './Route.js' from '/Users/Alessandro/ui/bower_components/rosso'
```

Apparently, browserify is trying to require './Route.js', which is already bundled into the 'Rosso.js' bundle file.

**Comment by cameronjroe** [comment]
Does browserify support requiring bower packages without the path? Would it be useful to include an option in the browserify config to look for bower packages via the main property? And for the concern of requiring duplicate modules via npm and bower one could specify the version or priority of the require conflict.

**Comment by goto-bus-stop** [comment]
the issue here was that the required file included `require()` calls, but that `require` was actually a local function. adding [derequire](https://github.com/calvinmetcalf/derequire) prevents that sort of thing from being an issue. closing bc it's been a long time
