### ISSUE TITLE
No globals with detectGlobals, insertGlobals config

### ISSUE THREAD

**Issue by JosephClay** [browserify/browserify#979]
I am bundling a project using:

```
browserify('path/to/file', { insertGlobals: true, detectGlobals: false });
```

The intent is to have a faster build, and have globals inserted. However, the build is faster but no globals (`process,global,Buffer,__argument0,__argument1,__argument2,__argument3,__filename,__dirname`) are inserted.

**Comment by goto-bus-stop** [comment]
Setting `detectGlobals` to false disables inserting globals entirely; just `browserify('/path/to/file', { insertGlobals: true })` does the trick.
