### ISSUE TITLE
Feature request - different entry point depending on "debug" setting

### ISSUE THREAD

**Issue by cconrad** [browserify/browserify#984]
With the "browser" attribute in package.json it is possible to have another entry point than "main" for Browserify bundling.

Would it be possible and make sense to make the entry point dependent on whether "debug" is set for the Browserify instance that resolves the entry point of the required module?

I.e. `"browser_debug": "./build/debug/index.js"` and `"browser": "./build/release/index.js"` in ones package.json file.

**Comment by goto-bus-stop** [comment]
i think the ecosystem has mostly settled on using `process.env.NODE_ENV` checks in the entry point to do this sort of thing. you can use envify and uglifyify to make that work efficiently.
