### ISSUE TITLE
Ability for a module to disallow itself from being included in a bundle

### ISSUE THREAD

**Issue by greim** [browserify/browserify#986]
Here's the use case. Some of our server-side modules have sensitive information, so I'd like to make it impossible to include them in any client side bundle. If a developer tries to do so, the build would fail during static analysis, similar to how if there were a syntax error or a `require()` to a non-existent module.

Using `exclude` doesn't work since it doesn't fail the build, but rather generates a bundle which fails at runtime. I have this hack in place that does what I want:

``` js
try { require('./doesnt/exist'); }
catch(ex) {}
```

...however that seems very ugly and a bit of a WTF for someone reading the code or puzzling over a build failure. It would be nice if the file could declare itself off-limits to browserify in a clean way. Something along the lines of:

``` js
/* @browserify disallow */
```

**Comment by goto-bus-stop** [comment]
i think this is quite a rare use case, and a global transform that detects a `/* @browserify disallow */` comment should work to implement the feature as requested in OP.
